#############################################################################
# Makefile for building: Rana_qt
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  Rana_qt.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile Rana_qt.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -Wextra -Wno-unused-variable -Wno-unused-parameter -O2 -o3 -std=c++1y -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/home/theis/workspace/RANA/../lua51_64bit/include -isystem /usr/include/lua5.1 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -IBUILD/moc -IBUILD/ui -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Rana_qt1.0.0
DISTDIR = /home/theis/workspace/RANA/BUILD/obj/Rana_qt1.0.0
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -largtable2 -L/usr/local/include/ -lbayesopt -lnlopt -llua5.1 -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = BUILD/obj/

####### Files

SOURCES       = src/main.cpp \
		src/cli.cpp \
		src/mainwindow.cpp \
		src/parser.cpp \
		src/output.cpp \
		src/control.cpp \
		src/graphics/agentItem.cpp \
		src/runner.cpp \
		src/postprocessing/eventprocessing.cpp \
		src/postprocessing/colorutility.cpp \
		src/eventdialog.cpp \
		src/postprocessing/graphics/zblock.cpp \
		src/postprocessing/postcontrol.cpp \
		src/postprocessing/eventrunner.cpp \
		src/postprocessing/graphics/zmap.cpp \
		src/helpdialog.cpp \
		src/api/gridmovement.cpp \
		src/api/maphandler.cpp \
		src/api/phys.cpp \
		src/api/scanning.cpp \
		src/api/shared.cpp \
		src/simulationcore/flowcontrol.cpp \
		src/simulationcore/interfacer.cpp \
		src/simulationcore/sector.cpp \
		src/simulationcore/supervisor.cpp \
		src/simulationcore/agents/agent.cpp \
		src/simulationcore/agents/agentluainterface.cpp \
		src/simulationcore/eventqueue.cpp \
		src/api/tcpserver.cpp \
		src/api/tcpclient.cpp \
		src/bopthook.cpp BUILD/rcc/qrc_images.cpp \
		BUILD/moc/moc_cli.cpp \
		BUILD/moc/moc_mainwindow.cpp \
		BUILD/moc/moc_control.cpp \
		BUILD/moc/moc_runner.cpp \
		BUILD/moc/moc_eventdialog.cpp \
		BUILD/moc/moc_postcontrol.cpp \
		BUILD/moc/moc_eventrunner.cpp \
		BUILD/moc/moc_helpdialog.cpp \
		BUILD/moc/moc_bopthook.cpp
OBJECTS       = BUILD/obj/main.o \
		BUILD/obj/cli.o \
		BUILD/obj/mainwindow.o \
		BUILD/obj/parser.o \
		BUILD/obj/output.o \
		BUILD/obj/control.o \
		BUILD/obj/agentItem.o \
		BUILD/obj/runner.o \
		BUILD/obj/eventprocessing.o \
		BUILD/obj/colorutility.o \
		BUILD/obj/eventdialog.o \
		BUILD/obj/zblock.o \
		BUILD/obj/postcontrol.o \
		BUILD/obj/eventrunner.o \
		BUILD/obj/zmap.o \
		BUILD/obj/helpdialog.o \
		BUILD/obj/gridmovement.o \
		BUILD/obj/maphandler.o \
		BUILD/obj/phys.o \
		BUILD/obj/scanning.o \
		BUILD/obj/shared.o \
		BUILD/obj/flowcontrol.o \
		BUILD/obj/interfacer.o \
		BUILD/obj/sector.o \
		BUILD/obj/supervisor.o \
		BUILD/obj/agent.o \
		BUILD/obj/agentluainterface.o \
		BUILD/obj/eventqueue.o \
		BUILD/obj/tcpserver.o \
		BUILD/obj/tcpclient.o \
		BUILD/obj/bopthook.o \
		BUILD/obj/qrc_images.o \
		BUILD/obj/moc_cli.o \
		BUILD/obj/moc_mainwindow.o \
		BUILD/obj/moc_control.o \
		BUILD/obj/moc_runner.o \
		BUILD/obj/moc_eventdialog.o \
		BUILD/obj/moc_postcontrol.o \
		BUILD/obj/moc_eventrunner.o \
		BUILD/obj/moc_helpdialog.o \
		BUILD/obj/moc_bopthook.o
DIST          = src/lua_agents/01_pingpong.lua \
		src/lua_agents/02_data_collector.lua \
		src/lua_agents/02_master.lua \
		src/lua_agents/02_oscillator.lua \
		src/lua_agents/03_painter.lua \
		src/lua_agents/04_valueShare.lua \
		src/lua_agents/05_angular_event_module.lua \
		src/lua_agents/05_bat.lua \
		src/lua_agents/05_master.lua \
		src/lua_agents/05_pole.lua \
		src/lua_agents/06_mover.lua \
		src/lua_agents/07_repulser.lua \
		src/lua_agents/08_flasher.lua \
		src/lua_agents/08_master_flasher.lua \
		src/lua_agents/09_radial_scanner.lua \
		src/lua_agents/10_pingpong_targeted.lua \
		src/lua_agents/11_data_collector.lua \
		src/lua_agents/11_forage_module.lua \
		src/lua_agents/11_frog.lua \
		src/lua_agents/11_master.lua \
		src/lua_agents/11_oscillator_module.lua \
		src/lua_agents/12_master.lua \
		src/lua_agents/13_precision_test.lua \
		src/lua_agents/15_master.lua \
		src/lua_agents/15_female.lua \
		src/lua_agents/15_freerunning_osc.lua \
		src/lua_agents/15_greenfield_osc.lua \
		src/lua_agents/16_neuron.lua \
		src/lua_agents/16_master.lua \
		src/lua_agents/17_lizard.lua \
		src/lua_agents/18_green.lua \
		src/lua_agents/18_microphone.lua \
		src/lua_agents/tcpInputAgent.lua \
		src/modules/auxiliary.lua \
		src/modules/lib_env_lake.lua \
		src/modules/lib_table.lua \
		src/modules/ranalib_agent.lua \
		src/modules/ranalib_api.lua \
		src/modules/ranalib_collision.lua \
		src/modules/ranalib_core.lua \
		src/modules/ranalib_draw.lua \
		src/modules/ranalib_environment.lua \
		src/modules/ranalib_event.lua \
		src/modules/ranalib_map.lua \
		src/modules/ranalib_movement.lua \
		src/modules/ranalib_shared.lua \
		src/modules/ranalib_statistic.lua \
		src/modules/ranalib_utility.lua \
		src/modules/ranalib_math.lua \
		src/modules/ranalib_physics.lua \
		src/modules/wrapper_auxiliary.lua \
		src/modules/ranalib_variable.lua \
		src/modules/test_file_input.lua \
		src/modules/ranalib_simconfig.lua \
		src/modules/test/test1_green_2.lua \
		src/modules/test/test1_green_3.lua \
		src/modules/test/test1_green_4.lua \
		src/modules/test/test1_green_5.lua \
		src/modules/test/test2_8012_green_2.lua \
		src/modules/test/test2_8012_green_3.lua \
		src/modules/test/test2_8012_green_4.lua \
		src/modules/test/test2_8012_green_5.lua \
		src/modules/test/test2_8017_green_2.lua \
		src/modules/test/test2_8017_green_3.lua \
		src/modules/test/test2_8017_green_4.lua \
		src/modules/test/test2_8017_green_5.lua \
		src/modules/test/test2_8133_green_2.lua \
		src/modules/test/test2_8133_green_3.lua \
		src/modules/test/test2_8133_green_4.lua \
		src/modules/test/test2_8133_green_5.lua \
		src/modules/test/test2_8164_green_2.lua \
		src/modules/test/test2_8164_green_3.lua \
		src/modules/test/test2_8164_green_4.lua \
		src/modules/test/test2_8164_green_5.lua \
		src/modules/test/test2_8254_green_2.lua \
		src/modules/test/test2_8254_green_3.lua \
		src/modules/test/test2_8254_green_4.lua \
		src/modules/test/test2_8254_green_5.lua \
		src/modules/lib_sim_config.lua \
		src/lua_agents/test_2_master.lua \
		src/lua_agents/test_1_master.lua \
		src/lua_agents/test_3_master.lua \
		src/lua_agents/test_4_master.lua \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++14.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Rana_qt.pro src/cli.h \
		src/mainwindow.h \
		src/parser.h \
		src/ID.h \
		src/utility.h \
		src/output.h \
		src/control.h \
		src/graphics/agentItem.h \
		src/runner.h \
		src/postprocessing/eventprocessing.h \
		src/postprocessing/colorutility.h \
		src/eventdialog.h \
		src/postprocessing/graphics/zblock.h \
		src/postprocessing/postcontrol.h \
		src/postprocessing/eventrunner.h \
		src/postprocessing/graphics/zmap.h \
		src/helpdialog.h \
		src/api/gridmovement.h \
		src/api/maphandler.h \
		src/api/phys.h \
		src/api/scanning.h \
		src/api/shared.h \
		src/simulationcore/flowcontrol.h \
		src/simulationcore/interfacer.h \
		src/simulationcore/sector.h \
		src/simulationcore/supervisor.h \
		src/simulationcore/agents/agent.h \
		src/simulationcore/agents/agentluainterface.h \
		src/simulationcore/eventqueue.h \
		src/api/tcpclient.h \
		src/api/tcpserver.h \
		src/bopthook.h src/main.cpp \
		src/cli.cpp \
		src/mainwindow.cpp \
		src/parser.cpp \
		src/output.cpp \
		src/control.cpp \
		src/graphics/agentItem.cpp \
		src/runner.cpp \
		src/postprocessing/eventprocessing.cpp \
		src/postprocessing/colorutility.cpp \
		src/eventdialog.cpp \
		src/postprocessing/graphics/zblock.cpp \
		src/postprocessing/postcontrol.cpp \
		src/postprocessing/eventrunner.cpp \
		src/postprocessing/graphics/zmap.cpp \
		src/helpdialog.cpp \
		src/api/gridmovement.cpp \
		src/api/maphandler.cpp \
		src/api/phys.cpp \
		src/api/scanning.cpp \
		src/api/shared.cpp \
		src/simulationcore/flowcontrol.cpp \
		src/simulationcore/interfacer.cpp \
		src/simulationcore/sector.cpp \
		src/simulationcore/supervisor.cpp \
		src/simulationcore/agents/agent.cpp \
		src/simulationcore/agents/agentluainterface.cpp \
		src/simulationcore/eventqueue.cpp \
		src/api/tcpserver.cpp \
		src/api/tcpclient.cpp \
		src/bopthook.cpp
QMAKE_TARGET  = Rana_qt
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = Rana_qt


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): BUILD/ui/ui_mainwindow.h BUILD/ui/ui_eventdialog.h BUILD/ui/ui_about.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Rana_qt.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++14.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Rana_qt.pro \
		resources/images.qrc \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile Rana_qt.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++14.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
Rana_qt.pro:
resources/images.qrc:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Rana_qt.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources/images.qrc $(DISTDIR)/
	$(COPY_FILE) --parents src/cli.h src/mainwindow.h src/parser.h src/ID.h src/utility.h src/output.h src/control.h src/graphics/agentItem.h src/runner.h src/postprocessing/eventprocessing.h src/postprocessing/colorutility.h src/eventdialog.h src/postprocessing/graphics/zblock.h src/postprocessing/postcontrol.h src/postprocessing/eventrunner.h src/postprocessing/graphics/zmap.h src/helpdialog.h src/api/gridmovement.h src/api/maphandler.h src/api/phys.h src/api/scanning.h src/api/shared.h src/simulationcore/flowcontrol.h src/simulationcore/interfacer.h src/simulationcore/sector.h src/simulationcore/supervisor.h src/simulationcore/agents/agent.h src/simulationcore/agents/agentluainterface.h src/simulationcore/eventqueue.h src/api/tcpclient.h src/api/tcpserver.h src/bopthook.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/cli.cpp src/mainwindow.cpp src/parser.cpp src/output.cpp src/control.cpp src/graphics/agentItem.cpp src/runner.cpp src/postprocessing/eventprocessing.cpp src/postprocessing/colorutility.cpp src/eventdialog.cpp src/postprocessing/graphics/zblock.cpp src/postprocessing/postcontrol.cpp src/postprocessing/eventrunner.cpp src/postprocessing/graphics/zmap.cpp src/helpdialog.cpp src/api/gridmovement.cpp src/api/maphandler.cpp src/api/phys.cpp src/api/scanning.cpp src/api/shared.cpp src/simulationcore/flowcontrol.cpp src/simulationcore/interfacer.cpp src/simulationcore/sector.cpp src/simulationcore/supervisor.cpp src/simulationcore/agents/agent.cpp src/simulationcore/agents/agentluainterface.cpp src/simulationcore/eventqueue.cpp src/api/tcpserver.cpp src/api/tcpclient.cpp src/bopthook.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ui/mainwindow.ui ui/eventdialog.ui ui/about.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

first: $(first) copydata

copydata:
	$(COPY_DIR) /home/theis/workspace/RANA/src/modules /home/theis/workspace/RANA

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: BUILD/rcc/qrc_images.cpp
compiler_rcc_clean:
	-$(DEL_FILE) BUILD/rcc/qrc_images.cpp
BUILD/rcc/qrc_images.cpp: resources/images.qrc \
		resources/images/ranalogo.png
	/usr/lib/x86_64-linux-gnu/qt5/bin/rcc -name images resources/images.qrc -o BUILD/rcc/qrc_images.cpp

compiler_moc_header_make_all: BUILD/moc/moc_cli.cpp BUILD/moc/moc_mainwindow.cpp BUILD/moc/moc_control.cpp BUILD/moc/moc_runner.cpp BUILD/moc/moc_eventdialog.cpp BUILD/moc/moc_postcontrol.cpp BUILD/moc/moc_eventrunner.cpp BUILD/moc/moc_helpdialog.cpp BUILD/moc/moc_bopthook.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) BUILD/moc/moc_cli.cpp BUILD/moc/moc_mainwindow.cpp BUILD/moc/moc_control.cpp BUILD/moc/moc_runner.cpp BUILD/moc/moc_eventdialog.cpp BUILD/moc/moc_postcontrol.cpp BUILD/moc/moc_eventrunner.cpp BUILD/moc/moc_helpdialog.cpp BUILD/moc/moc_bopthook.cpp
BUILD/moc/moc_cli.cpp: src/control.h \
		src/cli.h \
		src/utility.h \
		src/graphics/agentItem.h \
		src/postprocessing/postcontrol.h \
		src/postprocessing/eventrunner.h \
		src/postprocessing/eventprocessing.h \
		src/simulationcore/agents/agentluainterface.h \
		src/simulationcore/sector.h \
		src/simulationcore/supervisor.h \
		src/simulationcore/eventqueue.h \
		src/simulationcore/agents/agent.h \
		src/mainwindow.h \
		src/postprocessing/graphics/zblock.h \
		src/postprocessing/colorutility.h \
		src/postprocessing/graphics/zmap.h \
		src/bopthook.h \
		src/runner.h \
		src/simulationcore/flowcontrol.h \
		src/simulationcore/interfacer.h \
		src/parser.h \
		src/ID.h \
		src/api/phys.h \
		src/api/gridmovement.h \
		src/api/shared.h \
		src/output.h \
		src/api/scanning.h \
		src/api/tcpserver.h \
		src/cli.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/theis/workspace/RANA -I/home/theis/workspace/lua51_64bit/include -I/usr/include/lua5.1 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/cli.h -o BUILD/moc/moc_cli.cpp

BUILD/moc/moc_mainwindow.cpp: src/control.h \
		src/cli.h \
		src/utility.h \
		src/graphics/agentItem.h \
		src/postprocessing/postcontrol.h \
		src/postprocessing/eventrunner.h \
		src/postprocessing/eventprocessing.h \
		src/simulationcore/agents/agentluainterface.h \
		src/simulationcore/sector.h \
		src/simulationcore/supervisor.h \
		src/simulationcore/eventqueue.h \
		src/simulationcore/agents/agent.h \
		src/mainwindow.h \
		src/postprocessing/graphics/zblock.h \
		src/postprocessing/colorutility.h \
		src/postprocessing/graphics/zmap.h \
		src/bopthook.h \
		src/runner.h \
		src/simulationcore/flowcontrol.h \
		src/simulationcore/interfacer.h \
		src/parser.h \
		src/ID.h \
		src/api/phys.h \
		src/api/gridmovement.h \
		src/api/shared.h \
		src/output.h \
		src/api/scanning.h \
		src/api/tcpserver.h \
		src/mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/theis/workspace/RANA -I/home/theis/workspace/lua51_64bit/include -I/usr/include/lua5.1 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/mainwindow.h -o BUILD/moc/moc_mainwindow.cpp

BUILD/moc/moc_control.cpp: src/cli.h \
		src/control.h \
		src/mainwindow.h \
		src/utility.h \
		src/graphics/agentItem.h \
		src/postprocessing/postcontrol.h \
		src/postprocessing/eventrunner.h \
		src/postprocessing/eventprocessing.h \
		src/simulationcore/agents/agentluainterface.h \
		src/simulationcore/sector.h \
		src/simulationcore/supervisor.h \
		src/simulationcore/eventqueue.h \
		src/simulationcore/agents/agent.h \
		src/postprocessing/graphics/zblock.h \
		src/postprocessing/colorutility.h \
		src/postprocessing/graphics/zmap.h \
		src/runner.h \
		src/simulationcore/flowcontrol.h \
		src/simulationcore/interfacer.h \
		src/parser.h \
		src/ID.h \
		src/api/phys.h \
		src/api/gridmovement.h \
		src/api/shared.h \
		src/output.h \
		src/api/scanning.h \
		src/api/tcpserver.h \
		src/bopthook.h \
		src/control.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/theis/workspace/RANA -I/home/theis/workspace/lua51_64bit/include -I/usr/include/lua5.1 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/control.h -o BUILD/moc/moc_control.cpp

BUILD/moc/moc_runner.cpp: src/simulationcore/flowcontrol.h \
		src/simulationcore/interfacer.h \
		src/simulationcore/agents/agent.h \
		src/utility.h \
		src/simulationcore/eventqueue.h \
		src/simulationcore/agents/agentluainterface.h \
		src/simulationcore/sector.h \
		src/simulationcore/supervisor.h \
		src/mainwindow.h \
		src/control.h \
		src/cli.h \
		src/graphics/agentItem.h \
		src/postprocessing/postcontrol.h \
		src/postprocessing/eventrunner.h \
		src/postprocessing/eventprocessing.h \
		src/postprocessing/graphics/zblock.h \
		src/postprocessing/colorutility.h \
		src/postprocessing/graphics/zmap.h \
		src/bopthook.h \
		src/runner.h \
		src/parser.h \
		src/ID.h \
		src/api/phys.h \
		src/api/gridmovement.h \
		src/api/shared.h \
		src/output.h \
		src/api/scanning.h \
		src/api/tcpserver.h \
		src/runner.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/theis/workspace/RANA -I/home/theis/workspace/lua51_64bit/include -I/usr/include/lua5.1 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/runner.h -o BUILD/moc/moc_runner.cpp

BUILD/moc/moc_eventdialog.cpp: src/control.h \
		src/cli.h \
		src/utility.h \
		src/graphics/agentItem.h \
		src/postprocessing/postcontrol.h \
		src/postprocessing/eventrunner.h \
		src/postprocessing/eventprocessing.h \
		src/simulationcore/agents/agentluainterface.h \
		src/simulationcore/sector.h \
		src/simulationcore/supervisor.h \
		src/simulationcore/eventqueue.h \
		src/simulationcore/agents/agent.h \
		src/mainwindow.h \
		src/postprocessing/graphics/zblock.h \
		src/postprocessing/colorutility.h \
		src/postprocessing/graphics/zmap.h \
		src/bopthook.h \
		src/runner.h \
		src/simulationcore/flowcontrol.h \
		src/simulationcore/interfacer.h \
		src/parser.h \
		src/ID.h \
		src/api/phys.h \
		src/api/gridmovement.h \
		src/api/shared.h \
		src/output.h \
		src/api/scanning.h \
		src/api/tcpserver.h \
		src/eventdialog.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/theis/workspace/RANA -I/home/theis/workspace/lua51_64bit/include -I/usr/include/lua5.1 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/eventdialog.h -o BUILD/moc/moc_eventdialog.cpp

BUILD/moc/moc_postcontrol.cpp: src/postprocessing/eventrunner.h \
		src/postprocessing/eventprocessing.h \
		src/simulationcore/agents/agentluainterface.h \
		src/simulationcore/sector.h \
		src/simulationcore/supervisor.h \
		src/simulationcore/eventqueue.h \
		src/utility.h \
		src/simulationcore/agents/agent.h \
		src/mainwindow.h \
		src/control.h \
		src/cli.h \
		src/graphics/agentItem.h \
		src/postprocessing/postcontrol.h \
		src/postprocessing/graphics/zblock.h \
		src/postprocessing/colorutility.h \
		src/postprocessing/graphics/zmap.h \
		src/bopthook.h \
		src/runner.h \
		src/simulationcore/flowcontrol.h \
		src/simulationcore/interfacer.h \
		src/parser.h \
		src/ID.h \
		src/api/phys.h \
		src/api/gridmovement.h \
		src/api/shared.h \
		src/output.h \
		src/api/scanning.h \
		src/api/tcpserver.h \
		src/postprocessing/postcontrol.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/theis/workspace/RANA -I/home/theis/workspace/lua51_64bit/include -I/usr/include/lua5.1 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/postprocessing/postcontrol.h -o BUILD/moc/moc_postcontrol.cpp

BUILD/moc/moc_eventrunner.cpp: src/postprocessing/eventprocessing.h \
		src/simulationcore/agents/agentluainterface.h \
		src/simulationcore/sector.h \
		src/simulationcore/supervisor.h \
		src/simulationcore/eventqueue.h \
		src/utility.h \
		src/simulationcore/agents/agent.h \
		src/mainwindow.h \
		src/control.h \
		src/cli.h \
		src/graphics/agentItem.h \
		src/postprocessing/postcontrol.h \
		src/postprocessing/eventrunner.h \
		src/postprocessing/graphics/zblock.h \
		src/postprocessing/colorutility.h \
		src/postprocessing/graphics/zmap.h \
		src/bopthook.h \
		src/runner.h \
		src/simulationcore/flowcontrol.h \
		src/simulationcore/interfacer.h \
		src/parser.h \
		src/ID.h \
		src/api/phys.h \
		src/api/gridmovement.h \
		src/api/shared.h \
		src/output.h \
		src/api/scanning.h \
		src/api/tcpserver.h \
		src/postprocessing/eventrunner.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/theis/workspace/RANA -I/home/theis/workspace/lua51_64bit/include -I/usr/include/lua5.1 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/postprocessing/eventrunner.h -o BUILD/moc/moc_eventrunner.cpp

BUILD/moc/moc_helpdialog.cpp: src/helpdialog.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/theis/workspace/RANA -I/home/theis/workspace/lua51_64bit/include -I/usr/include/lua5.1 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/helpdialog.h -o BUILD/moc/moc_helpdialog.cpp

BUILD/moc/moc_bopthook.cpp: src/cli.h \
		src/control.h \
		src/mainwindow.h \
		src/utility.h \
		src/graphics/agentItem.h \
		src/postprocessing/postcontrol.h \
		src/postprocessing/eventrunner.h \
		src/postprocessing/eventprocessing.h \
		src/simulationcore/agents/agentluainterface.h \
		src/simulationcore/sector.h \
		src/simulationcore/supervisor.h \
		src/simulationcore/eventqueue.h \
		src/simulationcore/agents/agent.h \
		src/postprocessing/graphics/zblock.h \
		src/postprocessing/colorutility.h \
		src/postprocessing/graphics/zmap.h \
		src/runner.h \
		src/simulationcore/flowcontrol.h \
		src/simulationcore/interfacer.h \
		src/parser.h \
		src/ID.h \
		src/api/phys.h \
		src/api/gridmovement.h \
		src/api/shared.h \
		src/output.h \
		src/api/scanning.h \
		src/api/tcpserver.h \
		src/bopthook.h \
		src/bopthook.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/theis/workspace/RANA -I/home/theis/workspace/lua51_64bit/include -I/usr/include/lua5.1 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/bopthook.h -o BUILD/moc/moc_bopthook.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: BUILD/ui/ui_mainwindow.h BUILD/ui/ui_eventdialog.h BUILD/ui/ui_about.h
compiler_uic_clean:
	-$(DEL_FILE) BUILD/ui/ui_mainwindow.h BUILD/ui/ui_eventdialog.h BUILD/ui/ui_about.h
BUILD/ui/ui_mainwindow.h: ui/mainwindow.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ui/mainwindow.ui -o BUILD/ui/ui_mainwindow.h

BUILD/ui/ui_eventdialog.h: ui/eventdialog.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ui/eventdialog.ui -o BUILD/ui/ui_eventdialog.h

BUILD/ui/ui_about.h: ui/about.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ui/about.ui -o BUILD/ui/ui_about.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

BUILD/obj/main.o: src/main.cpp src/ID.h \
		src/cli.h \
		src/control.h \
		src/mainwindow.h \
		src/utility.h \
		src/graphics/agentItem.h \
		src/postprocessing/postcontrol.h \
		src/postprocessing/eventrunner.h \
		src/postprocessing/eventprocessing.h \
		src/simulationcore/agents/agentluainterface.h \
		src/simulationcore/sector.h \
		src/simulationcore/supervisor.h \
		src/simulationcore/eventqueue.h \
		src/simulationcore/agents/agent.h \
		src/postprocessing/graphics/zblock.h \
		src/postprocessing/colorutility.h \
		src/postprocessing/graphics/zmap.h \
		src/runner.h \
		src/simulationcore/flowcontrol.h \
		src/simulationcore/interfacer.h \
		src/parser.h \
		src/api/phys.h \
		src/api/gridmovement.h \
		src/api/shared.h \
		src/output.h \
		src/api/scanning.h \
		src/api/tcpserver.h \
		src/bopthook.h \
		src/api/tcpclient.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/obj/main.o src/main.cpp

BUILD/obj/cli.o: src/cli.cpp src/cli.h \
		src/control.h \
		src/mainwindow.h \
		src/utility.h \
		src/graphics/agentItem.h \
		src/postprocessing/postcontrol.h \
		src/postprocessing/eventrunner.h \
		src/postprocessing/eventprocessing.h \
		src/simulationcore/agents/agentluainterface.h \
		src/simulationcore/sector.h \
		src/simulationcore/supervisor.h \
		src/simulationcore/eventqueue.h \
		src/simulationcore/agents/agent.h \
		src/postprocessing/graphics/zblock.h \
		src/postprocessing/colorutility.h \
		src/postprocessing/graphics/zmap.h \
		src/runner.h \
		src/simulationcore/flowcontrol.h \
		src/simulationcore/interfacer.h \
		src/parser.h \
		src/ID.h \
		src/api/phys.h \
		src/api/gridmovement.h \
		src/api/shared.h \
		src/output.h \
		src/api/scanning.h \
		src/api/tcpserver.h \
		src/bopthook.h \
		src/api/maphandler.h \
		src/eventdialog.h \
		src/helpdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/obj/cli.o src/cli.cpp

BUILD/obj/mainwindow.o: src/mainwindow.cpp BUILD/ui/ui_mainwindow.h \
		src/mainwindow.h \
		src/control.h \
		src/cli.h \
		src/utility.h \
		src/graphics/agentItem.h \
		src/postprocessing/postcontrol.h \
		src/postprocessing/eventrunner.h \
		src/postprocessing/eventprocessing.h \
		src/simulationcore/agents/agentluainterface.h \
		src/simulationcore/sector.h \
		src/simulationcore/supervisor.h \
		src/simulationcore/eventqueue.h \
		src/simulationcore/agents/agent.h \
		src/postprocessing/graphics/zblock.h \
		src/postprocessing/colorutility.h \
		src/postprocessing/graphics/zmap.h \
		src/bopthook.h \
		src/runner.h \
		src/simulationcore/flowcontrol.h \
		src/simulationcore/interfacer.h \
		src/parser.h \
		src/ID.h \
		src/api/phys.h \
		src/api/gridmovement.h \
		src/api/shared.h \
		src/output.h \
		src/api/scanning.h \
		src/api/tcpserver.h \
		src/api/maphandler.h \
		src/eventdialog.h \
		src/helpdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/obj/mainwindow.o src/mainwindow.cpp

BUILD/obj/parser.o: src/parser.cpp src/parser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/obj/parser.o src/parser.cpp

BUILD/obj/output.o: src/output.cpp src/output.h \
		src/mainwindow.h \
		src/control.h \
		src/cli.h \
		src/utility.h \
		src/graphics/agentItem.h \
		src/postprocessing/postcontrol.h \
		src/postprocessing/eventrunner.h \
		src/postprocessing/eventprocessing.h \
		src/simulationcore/agents/agentluainterface.h \
		src/simulationcore/sector.h \
		src/simulationcore/supervisor.h \
		src/simulationcore/eventqueue.h \
		src/simulationcore/agents/agent.h \
		src/postprocessing/graphics/zblock.h \
		src/postprocessing/colorutility.h \
		src/postprocessing/graphics/zmap.h \
		src/bopthook.h \
		src/runner.h \
		src/simulationcore/flowcontrol.h \
		src/simulationcore/interfacer.h \
		src/parser.h \
		src/ID.h \
		src/api/phys.h \
		src/api/gridmovement.h \
		src/api/shared.h \
		src/api/scanning.h \
		src/api/tcpserver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/obj/output.o src/output.cpp

BUILD/obj/control.o: src/control.cpp src/control.h \
		src/cli.h \
		src/utility.h \
		src/graphics/agentItem.h \
		src/postprocessing/postcontrol.h \
		src/postprocessing/eventrunner.h \
		src/postprocessing/eventprocessing.h \
		src/simulationcore/agents/agentluainterface.h \
		src/simulationcore/sector.h \
		src/simulationcore/supervisor.h \
		src/simulationcore/eventqueue.h \
		src/simulationcore/agents/agent.h \
		src/mainwindow.h \
		src/postprocessing/graphics/zblock.h \
		src/postprocessing/colorutility.h \
		src/postprocessing/graphics/zmap.h \
		src/bopthook.h \
		src/runner.h \
		src/simulationcore/flowcontrol.h \
		src/simulationcore/interfacer.h \
		src/parser.h \
		src/ID.h \
		src/api/phys.h \
		src/api/gridmovement.h \
		src/api/shared.h \
		src/output.h \
		src/api/scanning.h \
		src/api/tcpserver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/obj/control.o src/control.cpp

BUILD/obj/agentItem.o: src/graphics/agentItem.cpp src/graphics/agentItem.h \
		src/utility.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/obj/agentItem.o src/graphics/agentItem.cpp

BUILD/obj/runner.o: src/runner.cpp src/runner.h \
		src/simulationcore/flowcontrol.h \
		src/simulationcore/interfacer.h \
		src/simulationcore/agents/agent.h \
		src/utility.h \
		src/simulationcore/eventqueue.h \
		src/simulationcore/agents/agentluainterface.h \
		src/simulationcore/sector.h \
		src/simulationcore/supervisor.h \
		src/mainwindow.h \
		src/control.h \
		src/cli.h \
		src/graphics/agentItem.h \
		src/postprocessing/postcontrol.h \
		src/postprocessing/eventrunner.h \
		src/postprocessing/eventprocessing.h \
		src/postprocessing/graphics/zblock.h \
		src/postprocessing/colorutility.h \
		src/postprocessing/graphics/zmap.h \
		src/bopthook.h \
		src/parser.h \
		src/ID.h \
		src/api/phys.h \
		src/api/gridmovement.h \
		src/api/shared.h \
		src/output.h \
		src/api/scanning.h \
		src/api/tcpserver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/obj/runner.o src/runner.cpp

BUILD/obj/eventprocessing.o: src/postprocessing/eventprocessing.cpp src/api/gridmovement.h \
		src/api/phys.h \
		src/api/shared.h \
		src/simulationcore/agents/agentluainterface.h \
		src/simulationcore/sector.h \
		src/simulationcore/supervisor.h \
		src/simulationcore/eventqueue.h \
		src/utility.h \
		src/simulationcore/agents/agent.h \
		src/postprocessing/eventprocessing.h \
		src/mainwindow.h \
		src/control.h \
		src/cli.h \
		src/graphics/agentItem.h \
		src/postprocessing/postcontrol.h \
		src/postprocessing/eventrunner.h \
		src/postprocessing/graphics/zblock.h \
		src/postprocessing/colorutility.h \
		src/postprocessing/graphics/zmap.h \
		src/bopthook.h \
		src/runner.h \
		src/simulationcore/flowcontrol.h \
		src/simulationcore/interfacer.h \
		src/parser.h \
		src/ID.h \
		src/output.h \
		src/api/scanning.h \
		src/api/tcpserver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/obj/eventprocessing.o src/postprocessing/eventprocessing.cpp

BUILD/obj/colorutility.o: src/postprocessing/colorutility.cpp src/postprocessing/colorutility.h \
		src/output.h \
		src/mainwindow.h \
		src/control.h \
		src/cli.h \
		src/utility.h \
		src/graphics/agentItem.h \
		src/postprocessing/postcontrol.h \
		src/postprocessing/eventrunner.h \
		src/postprocessing/eventprocessing.h \
		src/simulationcore/agents/agentluainterface.h \
		src/simulationcore/sector.h \
		src/simulationcore/supervisor.h \
		src/simulationcore/eventqueue.h \
		src/simulationcore/agents/agent.h \
		src/postprocessing/graphics/zblock.h \
		src/postprocessing/graphics/zmap.h \
		src/bopthook.h \
		src/runner.h \
		src/simulationcore/flowcontrol.h \
		src/simulationcore/interfacer.h \
		src/parser.h \
		src/ID.h \
		src/api/phys.h \
		src/api/gridmovement.h \
		src/api/shared.h \
		src/api/scanning.h \
		src/api/tcpserver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/obj/colorutility.o src/postprocessing/colorutility.cpp

BUILD/obj/eventdialog.o: src/eventdialog.cpp BUILD/ui/ui_eventdialog.h \
		src/eventdialog.h \
		src/control.h \
		src/cli.h \
		src/utility.h \
		src/graphics/agentItem.h \
		src/postprocessing/postcontrol.h \
		src/postprocessing/eventrunner.h \
		src/postprocessing/eventprocessing.h \
		src/simulationcore/agents/agentluainterface.h \
		src/simulationcore/sector.h \
		src/simulationcore/supervisor.h \
		src/simulationcore/eventqueue.h \
		src/simulationcore/agents/agent.h \
		src/mainwindow.h \
		src/postprocessing/graphics/zblock.h \
		src/postprocessing/colorutility.h \
		src/postprocessing/graphics/zmap.h \
		src/bopthook.h \
		src/runner.h \
		src/simulationcore/flowcontrol.h \
		src/simulationcore/interfacer.h \
		src/parser.h \
		src/ID.h \
		src/api/phys.h \
		src/api/gridmovement.h \
		src/api/shared.h \
		src/output.h \
		src/api/scanning.h \
		src/api/tcpserver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/obj/eventdialog.o src/eventdialog.cpp

BUILD/obj/zblock.o: src/postprocessing/graphics/zblock.cpp src/output.h \
		src/mainwindow.h \
		src/control.h \
		src/cli.h \
		src/utility.h \
		src/graphics/agentItem.h \
		src/postprocessing/postcontrol.h \
		src/postprocessing/eventrunner.h \
		src/postprocessing/eventprocessing.h \
		src/simulationcore/agents/agentluainterface.h \
		src/simulationcore/sector.h \
		src/simulationcore/supervisor.h \
		src/simulationcore/eventqueue.h \
		src/simulationcore/agents/agent.h \
		src/postprocessing/graphics/zblock.h \
		src/postprocessing/colorutility.h \
		src/postprocessing/graphics/zmap.h \
		src/bopthook.h \
		src/runner.h \
		src/simulationcore/flowcontrol.h \
		src/simulationcore/interfacer.h \
		src/parser.h \
		src/ID.h \
		src/api/phys.h \
		src/api/gridmovement.h \
		src/api/shared.h \
		src/api/scanning.h \
		src/api/tcpserver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/obj/zblock.o src/postprocessing/graphics/zblock.cpp

BUILD/obj/postcontrol.o: src/postprocessing/postcontrol.cpp src/output.h \
		src/mainwindow.h \
		src/control.h \
		src/cli.h \
		src/utility.h \
		src/graphics/agentItem.h \
		src/postprocessing/postcontrol.h \
		src/postprocessing/eventrunner.h \
		src/postprocessing/eventprocessing.h \
		src/simulationcore/agents/agentluainterface.h \
		src/simulationcore/sector.h \
		src/simulationcore/supervisor.h \
		src/simulationcore/eventqueue.h \
		src/simulationcore/agents/agent.h \
		src/postprocessing/graphics/zblock.h \
		src/postprocessing/colorutility.h \
		src/postprocessing/graphics/zmap.h \
		src/bopthook.h \
		src/runner.h \
		src/simulationcore/flowcontrol.h \
		src/simulationcore/interfacer.h \
		src/parser.h \
		src/ID.h \
		src/api/phys.h \
		src/api/gridmovement.h \
		src/api/shared.h \
		src/api/scanning.h \
		src/api/tcpserver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/obj/postcontrol.o src/postprocessing/postcontrol.cpp

BUILD/obj/eventrunner.o: src/postprocessing/eventrunner.cpp src/output.h \
		src/mainwindow.h \
		src/control.h \
		src/cli.h \
		src/utility.h \
		src/graphics/agentItem.h \
		src/postprocessing/postcontrol.h \
		src/postprocessing/eventrunner.h \
		src/postprocessing/eventprocessing.h \
		src/simulationcore/agents/agentluainterface.h \
		src/simulationcore/sector.h \
		src/simulationcore/supervisor.h \
		src/simulationcore/eventqueue.h \
		src/simulationcore/agents/agent.h \
		src/postprocessing/graphics/zblock.h \
		src/postprocessing/colorutility.h \
		src/postprocessing/graphics/zmap.h \
		src/bopthook.h \
		src/runner.h \
		src/simulationcore/flowcontrol.h \
		src/simulationcore/interfacer.h \
		src/parser.h \
		src/ID.h \
		src/api/phys.h \
		src/api/gridmovement.h \
		src/api/shared.h \
		src/api/scanning.h \
		src/api/tcpserver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/obj/eventrunner.o src/postprocessing/eventrunner.cpp

BUILD/obj/zmap.o: src/postprocessing/graphics/zmap.cpp src/postprocessing/graphics/zmap.h \
		src/postprocessing/graphics/zblock.h \
		src/postprocessing/colorutility.h \
		src/output.h \
		src/mainwindow.h \
		src/control.h \
		src/cli.h \
		src/utility.h \
		src/graphics/agentItem.h \
		src/postprocessing/postcontrol.h \
		src/postprocessing/eventrunner.h \
		src/postprocessing/eventprocessing.h \
		src/simulationcore/agents/agentluainterface.h \
		src/simulationcore/sector.h \
		src/simulationcore/supervisor.h \
		src/simulationcore/eventqueue.h \
		src/simulationcore/agents/agent.h \
		src/bopthook.h \
		src/runner.h \
		src/simulationcore/flowcontrol.h \
		src/simulationcore/interfacer.h \
		src/parser.h \
		src/ID.h \
		src/api/phys.h \
		src/api/gridmovement.h \
		src/api/shared.h \
		src/api/scanning.h \
		src/api/tcpserver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/obj/zmap.o src/postprocessing/graphics/zmap.cpp

BUILD/obj/helpdialog.o: src/helpdialog.cpp src/helpdialog.h \
		BUILD/ui/ui_about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/obj/helpdialog.o src/helpdialog.cpp

BUILD/obj/gridmovement.o: src/api/gridmovement.cpp src/api/gridmovement.h \
		src/output.h \
		src/mainwindow.h \
		src/control.h \
		src/cli.h \
		src/utility.h \
		src/graphics/agentItem.h \
		src/postprocessing/postcontrol.h \
		src/postprocessing/eventrunner.h \
		src/postprocessing/eventprocessing.h \
		src/simulationcore/agents/agentluainterface.h \
		src/simulationcore/sector.h \
		src/simulationcore/supervisor.h \
		src/simulationcore/eventqueue.h \
		src/simulationcore/agents/agent.h \
		src/postprocessing/graphics/zblock.h \
		src/postprocessing/colorutility.h \
		src/postprocessing/graphics/zmap.h \
		src/bopthook.h \
		src/runner.h \
		src/simulationcore/flowcontrol.h \
		src/simulationcore/interfacer.h \
		src/parser.h \
		src/ID.h \
		src/api/phys.h \
		src/api/shared.h \
		src/api/scanning.h \
		src/api/tcpserver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/obj/gridmovement.o src/api/gridmovement.cpp

BUILD/obj/maphandler.o: src/api/maphandler.cpp src/output.h \
		src/mainwindow.h \
		src/control.h \
		src/cli.h \
		src/utility.h \
		src/graphics/agentItem.h \
		src/postprocessing/postcontrol.h \
		src/postprocessing/eventrunner.h \
		src/postprocessing/eventprocessing.h \
		src/simulationcore/agents/agentluainterface.h \
		src/simulationcore/sector.h \
		src/simulationcore/supervisor.h \
		src/simulationcore/eventqueue.h \
		src/simulationcore/agents/agent.h \
		src/postprocessing/graphics/zblock.h \
		src/postprocessing/colorutility.h \
		src/postprocessing/graphics/zmap.h \
		src/bopthook.h \
		src/runner.h \
		src/simulationcore/flowcontrol.h \
		src/simulationcore/interfacer.h \
		src/parser.h \
		src/ID.h \
		src/api/phys.h \
		src/api/gridmovement.h \
		src/api/shared.h \
		src/api/scanning.h \
		src/api/tcpserver.h \
		src/api/maphandler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/obj/maphandler.o src/api/maphandler.cpp

BUILD/obj/phys.o: src/api/phys.cpp src/api/phys.h \
		src/output.h \
		src/mainwindow.h \
		src/control.h \
		src/cli.h \
		src/utility.h \
		src/graphics/agentItem.h \
		src/postprocessing/postcontrol.h \
		src/postprocessing/eventrunner.h \
		src/postprocessing/eventprocessing.h \
		src/simulationcore/agents/agentluainterface.h \
		src/simulationcore/sector.h \
		src/simulationcore/supervisor.h \
		src/simulationcore/eventqueue.h \
		src/simulationcore/agents/agent.h \
		src/postprocessing/graphics/zblock.h \
		src/postprocessing/colorutility.h \
		src/postprocessing/graphics/zmap.h \
		src/bopthook.h \
		src/runner.h \
		src/simulationcore/flowcontrol.h \
		src/simulationcore/interfacer.h \
		src/parser.h \
		src/ID.h \
		src/api/gridmovement.h \
		src/api/shared.h \
		src/api/scanning.h \
		src/api/tcpserver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/obj/phys.o src/api/phys.cpp

BUILD/obj/scanning.o: src/api/scanning.cpp src/api/scanning.h \
		src/utility.h \
		src/api/phys.h \
		src/output.h \
		src/mainwindow.h \
		src/control.h \
		src/cli.h \
		src/graphics/agentItem.h \
		src/postprocessing/postcontrol.h \
		src/postprocessing/eventrunner.h \
		src/postprocessing/eventprocessing.h \
		src/simulationcore/agents/agentluainterface.h \
		src/simulationcore/sector.h \
		src/simulationcore/supervisor.h \
		src/simulationcore/eventqueue.h \
		src/simulationcore/agents/agent.h \
		src/postprocessing/graphics/zblock.h \
		src/postprocessing/colorutility.h \
		src/postprocessing/graphics/zmap.h \
		src/bopthook.h \
		src/runner.h \
		src/simulationcore/flowcontrol.h \
		src/simulationcore/interfacer.h \
		src/parser.h \
		src/ID.h \
		src/api/gridmovement.h \
		src/api/shared.h \
		src/api/tcpserver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/obj/scanning.o src/api/scanning.cpp

BUILD/obj/shared.o: src/api/shared.cpp src/output.h \
		src/mainwindow.h \
		src/control.h \
		src/cli.h \
		src/utility.h \
		src/graphics/agentItem.h \
		src/postprocessing/postcontrol.h \
		src/postprocessing/eventrunner.h \
		src/postprocessing/eventprocessing.h \
		src/simulationcore/agents/agentluainterface.h \
		src/simulationcore/sector.h \
		src/simulationcore/supervisor.h \
		src/simulationcore/eventqueue.h \
		src/simulationcore/agents/agent.h \
		src/postprocessing/graphics/zblock.h \
		src/postprocessing/colorutility.h \
		src/postprocessing/graphics/zmap.h \
		src/bopthook.h \
		src/runner.h \
		src/simulationcore/flowcontrol.h \
		src/simulationcore/interfacer.h \
		src/parser.h \
		src/ID.h \
		src/api/phys.h \
		src/api/gridmovement.h \
		src/api/shared.h \
		src/api/scanning.h \
		src/api/tcpserver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/obj/shared.o src/api/shared.cpp

BUILD/obj/flowcontrol.o: src/simulationcore/flowcontrol.cpp src/simulationcore/flowcontrol.h \
		src/simulationcore/interfacer.h \
		src/simulationcore/agents/agent.h \
		src/utility.h \
		src/simulationcore/eventqueue.h \
		src/simulationcore/agents/agentluainterface.h \
		src/simulationcore/sector.h \
		src/simulationcore/supervisor.h \
		src/mainwindow.h \
		src/control.h \
		src/cli.h \
		src/graphics/agentItem.h \
		src/postprocessing/postcontrol.h \
		src/postprocessing/eventrunner.h \
		src/postprocessing/eventprocessing.h \
		src/postprocessing/graphics/zblock.h \
		src/postprocessing/colorutility.h \
		src/postprocessing/graphics/zmap.h \
		src/bopthook.h \
		src/runner.h \
		src/parser.h \
		src/ID.h \
		src/api/phys.h \
		src/api/gridmovement.h \
		src/api/shared.h \
		src/output.h \
		src/api/scanning.h \
		src/api/tcpserver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/obj/flowcontrol.o src/simulationcore/flowcontrol.cpp

BUILD/obj/interfacer.o: src/simulationcore/interfacer.cpp src/output.h \
		src/mainwindow.h \
		src/control.h \
		src/cli.h \
		src/utility.h \
		src/graphics/agentItem.h \
		src/postprocessing/postcontrol.h \
		src/postprocessing/eventrunner.h \
		src/postprocessing/eventprocessing.h \
		src/simulationcore/agents/agentluainterface.h \
		src/simulationcore/sector.h \
		src/simulationcore/supervisor.h \
		src/simulationcore/eventqueue.h \
		src/simulationcore/agents/agent.h \
		src/postprocessing/graphics/zblock.h \
		src/postprocessing/colorutility.h \
		src/postprocessing/graphics/zmap.h \
		src/bopthook.h \
		src/runner.h \
		src/simulationcore/flowcontrol.h \
		src/simulationcore/interfacer.h \
		src/parser.h \
		src/ID.h \
		src/api/phys.h \
		src/api/gridmovement.h \
		src/api/shared.h \
		src/api/scanning.h \
		src/api/tcpserver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/obj/interfacer.o src/simulationcore/interfacer.cpp

BUILD/obj/sector.o: src/simulationcore/sector.cpp src/ID.h \
		src/output.h \
		src/mainwindow.h \
		src/control.h \
		src/cli.h \
		src/utility.h \
		src/graphics/agentItem.h \
		src/postprocessing/postcontrol.h \
		src/postprocessing/eventrunner.h \
		src/postprocessing/eventprocessing.h \
		src/simulationcore/agents/agentluainterface.h \
		src/simulationcore/sector.h \
		src/simulationcore/supervisor.h \
		src/simulationcore/eventqueue.h \
		src/simulationcore/agents/agent.h \
		src/postprocessing/graphics/zblock.h \
		src/postprocessing/colorutility.h \
		src/postprocessing/graphics/zmap.h \
		src/bopthook.h \
		src/runner.h \
		src/simulationcore/flowcontrol.h \
		src/simulationcore/interfacer.h \
		src/parser.h \
		src/api/phys.h \
		src/api/gridmovement.h \
		src/api/shared.h \
		src/api/scanning.h \
		src/api/tcpserver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/obj/sector.o src/simulationcore/sector.cpp

BUILD/obj/supervisor.o: src/simulationcore/supervisor.cpp src/output.h \
		src/mainwindow.h \
		src/control.h \
		src/cli.h \
		src/utility.h \
		src/graphics/agentItem.h \
		src/postprocessing/postcontrol.h \
		src/postprocessing/eventrunner.h \
		src/postprocessing/eventprocessing.h \
		src/simulationcore/agents/agentluainterface.h \
		src/simulationcore/sector.h \
		src/simulationcore/supervisor.h \
		src/simulationcore/eventqueue.h \
		src/simulationcore/agents/agent.h \
		src/postprocessing/graphics/zblock.h \
		src/postprocessing/colorutility.h \
		src/postprocessing/graphics/zmap.h \
		src/bopthook.h \
		src/runner.h \
		src/simulationcore/flowcontrol.h \
		src/simulationcore/interfacer.h \
		src/parser.h \
		src/ID.h \
		src/api/phys.h \
		src/api/gridmovement.h \
		src/api/shared.h \
		src/api/scanning.h \
		src/api/tcpserver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/obj/supervisor.o src/simulationcore/supervisor.cpp

BUILD/obj/agent.o: src/simulationcore/agents/agent.cpp src/simulationcore/sector.h \
		src/simulationcore/supervisor.h \
		src/simulationcore/eventqueue.h \
		src/utility.h \
		src/simulationcore/agents/agentluainterface.h \
		src/simulationcore/agents/agent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/obj/agent.o src/simulationcore/agents/agent.cpp

BUILD/obj/agentluainterface.o: src/simulationcore/agents/agentluainterface.cpp src/ID.h \
		src/output.h \
		src/mainwindow.h \
		src/control.h \
		src/cli.h \
		src/utility.h \
		src/graphics/agentItem.h \
		src/postprocessing/postcontrol.h \
		src/postprocessing/eventrunner.h \
		src/postprocessing/eventprocessing.h \
		src/simulationcore/agents/agentluainterface.h \
		src/simulationcore/sector.h \
		src/simulationcore/supervisor.h \
		src/simulationcore/eventqueue.h \
		src/simulationcore/agents/agent.h \
		src/postprocessing/graphics/zblock.h \
		src/postprocessing/colorutility.h \
		src/postprocessing/graphics/zmap.h \
		src/bopthook.h \
		src/runner.h \
		src/simulationcore/flowcontrol.h \
		src/simulationcore/interfacer.h \
		src/parser.h \
		src/api/phys.h \
		src/api/gridmovement.h \
		src/api/shared.h \
		src/api/scanning.h \
		src/api/tcpserver.h \
		src/api/maphandler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/obj/agentluainterface.o src/simulationcore/agents/agentluainterface.cpp

BUILD/obj/eventqueue.o: src/simulationcore/eventqueue.cpp src/ID.h \
		src/output.h \
		src/mainwindow.h \
		src/control.h \
		src/cli.h \
		src/utility.h \
		src/graphics/agentItem.h \
		src/postprocessing/postcontrol.h \
		src/postprocessing/eventrunner.h \
		src/postprocessing/eventprocessing.h \
		src/simulationcore/agents/agentluainterface.h \
		src/simulationcore/sector.h \
		src/simulationcore/supervisor.h \
		src/simulationcore/eventqueue.h \
		src/simulationcore/agents/agent.h \
		src/postprocessing/graphics/zblock.h \
		src/postprocessing/colorutility.h \
		src/postprocessing/graphics/zmap.h \
		src/bopthook.h \
		src/runner.h \
		src/simulationcore/flowcontrol.h \
		src/simulationcore/interfacer.h \
		src/parser.h \
		src/api/phys.h \
		src/api/gridmovement.h \
		src/api/shared.h \
		src/api/scanning.h \
		src/api/tcpserver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/obj/eventqueue.o src/simulationcore/eventqueue.cpp

BUILD/obj/tcpserver.o: src/api/tcpserver.cpp src/api/tcpserver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/obj/tcpserver.o src/api/tcpserver.cpp

BUILD/obj/tcpclient.o: src/api/tcpclient.cpp src/api/tcpclient.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/obj/tcpclient.o src/api/tcpclient.cpp

BUILD/obj/bopthook.o: src/bopthook.cpp src/bopthook.h \
		src/cli.h \
		src/control.h \
		src/mainwindow.h \
		src/utility.h \
		src/graphics/agentItem.h \
		src/postprocessing/postcontrol.h \
		src/postprocessing/eventrunner.h \
		src/postprocessing/eventprocessing.h \
		src/simulationcore/agents/agentluainterface.h \
		src/simulationcore/sector.h \
		src/simulationcore/supervisor.h \
		src/simulationcore/eventqueue.h \
		src/simulationcore/agents/agent.h \
		src/postprocessing/graphics/zblock.h \
		src/postprocessing/colorutility.h \
		src/postprocessing/graphics/zmap.h \
		src/runner.h \
		src/simulationcore/flowcontrol.h \
		src/simulationcore/interfacer.h \
		src/parser.h \
		src/ID.h \
		src/api/phys.h \
		src/api/gridmovement.h \
		src/api/shared.h \
		src/output.h \
		src/api/scanning.h \
		src/api/tcpserver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/obj/bopthook.o src/bopthook.cpp

BUILD/obj/qrc_images.o: BUILD/rcc/qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/obj/qrc_images.o BUILD/rcc/qrc_images.cpp

BUILD/obj/moc_cli.o: BUILD/moc/moc_cli.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/obj/moc_cli.o BUILD/moc/moc_cli.cpp

BUILD/obj/moc_mainwindow.o: BUILD/moc/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/obj/moc_mainwindow.o BUILD/moc/moc_mainwindow.cpp

BUILD/obj/moc_control.o: BUILD/moc/moc_control.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/obj/moc_control.o BUILD/moc/moc_control.cpp

BUILD/obj/moc_runner.o: BUILD/moc/moc_runner.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/obj/moc_runner.o BUILD/moc/moc_runner.cpp

BUILD/obj/moc_eventdialog.o: BUILD/moc/moc_eventdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/obj/moc_eventdialog.o BUILD/moc/moc_eventdialog.cpp

BUILD/obj/moc_postcontrol.o: BUILD/moc/moc_postcontrol.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/obj/moc_postcontrol.o BUILD/moc/moc_postcontrol.cpp

BUILD/obj/moc_eventrunner.o: BUILD/moc/moc_eventrunner.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/obj/moc_eventrunner.o BUILD/moc/moc_eventrunner.cpp

BUILD/obj/moc_helpdialog.o: BUILD/moc/moc_helpdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/obj/moc_helpdialog.o BUILD/moc/moc_helpdialog.cpp

BUILD/obj/moc_bopthook.o: BUILD/moc/moc_bopthook.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BUILD/obj/moc_bopthook.o BUILD/moc/moc_bopthook.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

