#############################################################################
# Makefile for building: Rana_qt
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  Rana_qt.pro
# Template: app
# Command: /usr/lib/qt/bin/qmake -o Makefile Rana_qt.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -Wno-unused-variable -Wno-unused-parameter -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/home/sojoe/qtProjects/Rana_qt/../lua51_64bit/include -isystem /usr/include/luajit-2.0 -isystem /usr/include/qt -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-g++
QMAKE         = /usr/lib/qt/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Rana_qt1.0.0
DISTDIR = /home/sojoe/qtProjects/Rana_qt/.tmp/Rana_qt1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-O1,--sort-common,--as-needed,-z,relro
LIBS          = $(SUBLIBS) -lluajit-5.1 -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		eventqueue.cpp \
		physics/phys.cpp \
		agentengine/agents/nestene.cpp \
		agentengine/agents/auton.cpp \
		agentengine/agents/autonlistener.cpp \
		agentengine/agents/autonLUA.cpp \
		agentengine/agents/autonscreamer.cpp \
		agentengine/agents/doctor.cpp \
		agentengine/agents/master.cpp \
		agentengine/agentdomain.cpp \
		output.cpp \
		physics/maphandler.cpp \
		control.cpp \
		graphics/agentItem.cpp \
		physics/gridmovement.cpp \
		runner.cpp \
		physics/shared.cpp \
		postprocessing/eventprocessing.cpp \
		postprocessing/eventmap.cpp \
		graphics/zcolormap.cpp \
		postprocessing/colorutility.cpp \
		eventdialog.cpp \
		postprocessing/graphics/zblock.cpp \
		postprocessing/postcontrol.cpp \
		postprocessing/eventrunner.cpp \
		postprocessing/graphics/zmap.cpp \
		physics/scanning.cpp \
		helpdialog.cpp qrc_images.cpp \
		moc_mainwindow.cpp \
		moc_control.cpp \
		moc_runner.cpp \
		moc_eventdialog.cpp \
		moc_postcontrol.cpp \
		moc_eventrunner.cpp \
		moc_helpdialog.cpp
OBJECTS       = main.o \
		mainwindow.o \
		eventqueue.o \
		phys.o \
		nestene.o \
		auton.o \
		autonlistener.o \
		autonLUA.o \
		autonscreamer.o \
		doctor.o \
		master.o \
		agentdomain.o \
		output.o \
		maphandler.o \
		control.o \
		agentItem.o \
		gridmovement.o \
		runner.o \
		shared.o \
		eventprocessing.o \
		eventmap.o \
		zcolormap.o \
		colorutility.o \
		eventdialog.o \
		zblock.o \
		postcontrol.o \
		eventrunner.o \
		zmap.o \
		scanning.o \
		helpdialog.o \
		qrc_images.o \
		moc_mainwindow.o \
		moc_control.o \
		moc_runner.o \
		moc_eventdialog.o \
		moc_postcontrol.o \
		moc_eventrunner.o \
		moc_helpdialog.o
DIST          = /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_Attica.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/qt/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDEWebKit.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri \
		/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KHtml.pri \
		/usr/lib/qt/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJS.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJSApi.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/qt/mkspecs/modules/qt_KParts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPlotting.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPty.pri \
		/usr/lib/qt/mkspecs/modules/qt_KService.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib/qt/mkspecs/modules/qt_QGpgme.pri \
		/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_Solid.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		Rana_qt.pro mainwindow.h \
		physics/phys.h \
		agentengine/agents/nestene.h \
		agentengine/agents/auton.h \
		agentengine/agents/autonlistener.h \
		agentengine/agents/autonLUA.h \
		agentengine/agents/autonscreamer.h \
		agentengine/agents/doctor.h \
		agentengine/agents/master.h \
		agentengine/agentdomain.h \
		eventqueue.h \
		ID.h \
		utility.h \
		output.h \
		physics/maphandler.h \
		control.h \
		graphics/agentItem.h \
		physics/gridmovement.h \
		runner.h \
		physics/shared.h \
		postprocessing/eventprocessing.h \
		postprocessing/eventmap.h \
		graphics/zcolormap.h \
		postprocessing/colorutility.h \
		eventdialog.h \
		postprocessing/graphics/zblock.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/graphics/zmap.h \
		physics/scanning.h \
		helpdialog.h main.cpp \
		mainwindow.cpp \
		eventqueue.cpp \
		physics/phys.cpp \
		agentengine/agents/nestene.cpp \
		agentengine/agents/auton.cpp \
		agentengine/agents/autonlistener.cpp \
		agentengine/agents/autonLUA.cpp \
		agentengine/agents/autonscreamer.cpp \
		agentengine/agents/doctor.cpp \
		agentengine/agents/master.cpp \
		agentengine/agentdomain.cpp \
		output.cpp \
		physics/maphandler.cpp \
		control.cpp \
		graphics/agentItem.cpp \
		physics/gridmovement.cpp \
		runner.cpp \
		physics/shared.cpp \
		postprocessing/eventprocessing.cpp \
		postprocessing/eventmap.cpp \
		graphics/zcolormap.cpp \
		postprocessing/colorutility.cpp \
		eventdialog.cpp \
		postprocessing/graphics/zblock.cpp \
		postprocessing/postcontrol.cpp \
		postprocessing/eventrunner.cpp \
		postprocessing/graphics/zmap.cpp \
		physics/scanning.cpp \
		helpdialog.cpp
QMAKE_TARGET  = Rana_qt
DESTDIR       = 
TARGET        = Rana_qt


first: all
####### Build rules

$(TARGET): ui_mainwindow.h ui_eventdialog.h ui_about.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Rana_qt.pro /usr/lib/qt/mkspecs/linux-g++/qmake.conf /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_Attica.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/qt/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDEWebKit.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri \
		/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KHtml.pri \
		/usr/lib/qt/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJS.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJSApi.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/qt/mkspecs/modules/qt_KParts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPlotting.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPty.pri \
		/usr/lib/qt/mkspecs/modules/qt_KService.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib/qt/mkspecs/modules/qt_QGpgme.pri \
		/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_Solid.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		Rana_qt.pro \
		images.qrc \
		/usr/lib/libQt5Widgets.prl \
		/usr/lib/libQt5Gui.prl \
		/usr/lib/libQt5Core.prl
	$(QMAKE) -o Makefile Rana_qt.pro
/usr/lib/qt/mkspecs/features/spec_pre.prf:
/usr/lib/qt/mkspecs/common/unix.conf:
/usr/lib/qt/mkspecs/common/linux.conf:
/usr/lib/qt/mkspecs/common/sanitize.conf:
/usr/lib/qt/mkspecs/common/gcc-base.conf:
/usr/lib/qt/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt/mkspecs/common/g++-base.conf:
/usr/lib/qt/mkspecs/common/g++-unix.conf:
/usr/lib/qt/mkspecs/qconfig.pri:
/usr/lib/qt/mkspecs/modules/qt_Attica.pri:
/usr/lib/qt/mkspecs/modules/qt_KActivities.pri:
/usr/lib/qt/mkspecs/modules/qt_KArchive.pri:
/usr/lib/qt/mkspecs/modules/qt_KAuth.pri:
/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri:
/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri:
/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri:
/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KCrash.pri:
/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri:
/usr/lib/qt/mkspecs/modules/qt_KDEWebKit.pri:
/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri:
/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri:
/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri:
/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KHtml.pri:
/usr/lib/qt/mkspecs/modules/qt_KI18n.pri:
/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri:
/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri:
/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri:
/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KJS.pri:
/usr/lib/qt/mkspecs/modules/qt_KJSApi.pri:
/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri:
/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri:
/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri:
/usr/lib/qt/mkspecs/modules/qt_KParts.pri:
/usr/lib/qt/mkspecs/modules/qt_KPlotting.pri:
/usr/lib/qt/mkspecs/modules/qt_KPty.pri:
/usr/lib/qt/mkspecs/modules/qt_KService.pri:
/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri:
/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri:
/usr/lib/qt/mkspecs/modules/qt_KWallet.pri:
/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri:
/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_script.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri:
/usr/lib/qt/mkspecs/modules/qt_QGpgme.pri:
/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_Solid.pri:
/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri:
/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri:
/usr/lib/qt/mkspecs/features/qt_functions.prf:
/usr/lib/qt/mkspecs/features/qt_config.prf:
/usr/lib/qt/mkspecs/linux-g++/qmake.conf:
/usr/lib/qt/mkspecs/features/spec_post.prf:
/usr/lib/qt/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt/mkspecs/features/default_pre.prf:
/usr/lib/qt/mkspecs/features/resolve_config.prf:
/usr/lib/qt/mkspecs/features/default_post.prf:
/usr/lib/qt/mkspecs/features/link_pkgconfig.prf:
/usr/lib/qt/mkspecs/features/warn_on.prf:
/usr/lib/qt/mkspecs/features/qt.prf:
/usr/lib/qt/mkspecs/features/resources.prf:
/usr/lib/qt/mkspecs/features/moc.prf:
/usr/lib/qt/mkspecs/features/unix/opengl.prf:
/usr/lib/qt/mkspecs/features/uic.prf:
/usr/lib/qt/mkspecs/features/unix/thread.prf:
/usr/lib/qt/mkspecs/features/file_copies.prf:
/usr/lib/qt/mkspecs/features/testcase_targets.prf:
/usr/lib/qt/mkspecs/features/exceptions.prf:
/usr/lib/qt/mkspecs/features/yacc.prf:
/usr/lib/qt/mkspecs/features/lex.prf:
Rana_qt.pro:
images.qrc:
/usr/lib/libQt5Widgets.prl:
/usr/lib/libQt5Gui.prl:
/usr/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Rana_qt.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents images.qrc $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h physics/phys.h agentengine/agents/nestene.h agentengine/agents/auton.h agentengine/agents/autonlistener.h agentengine/agents/autonLUA.h agentengine/agents/autonscreamer.h agentengine/agents/doctor.h agentengine/agents/master.h agentengine/agentdomain.h eventqueue.h ID.h utility.h output.h physics/maphandler.h control.h graphics/agentItem.h physics/gridmovement.h runner.h physics/shared.h postprocessing/eventprocessing.h postprocessing/eventmap.h graphics/zcolormap.h postprocessing/colorutility.h eventdialog.h postprocessing/graphics/zblock.h postprocessing/postcontrol.h postprocessing/eventrunner.h postprocessing/graphics/zmap.h physics/scanning.h helpdialog.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp eventqueue.cpp physics/phys.cpp agentengine/agents/nestene.cpp agentengine/agents/auton.cpp agentengine/agents/autonlistener.cpp agentengine/agents/autonLUA.cpp agentengine/agents/autonscreamer.cpp agentengine/agents/doctor.cpp agentengine/agents/master.cpp agentengine/agentdomain.cpp output.cpp physics/maphandler.cpp control.cpp graphics/agentItem.cpp physics/gridmovement.cpp runner.cpp physics/shared.cpp postprocessing/eventprocessing.cpp postprocessing/eventmap.cpp graphics/zcolormap.cpp postprocessing/colorutility.cpp eventdialog.cpp postprocessing/graphics/zblock.cpp postprocessing/postcontrol.cpp postprocessing/eventrunner.cpp postprocessing/graphics/zmap.cpp physics/scanning.cpp helpdialog.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui eventdialog.ui about.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

first: $(first) copydata

copydata:
	$(COPY_DIR) /home/sojoe/qtProjects/Rana_qt/modules /home/sojoe/qtProjects/Rana_qt

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_images.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_images.cpp
qrc_images.cpp: images.qrc \
		/usr/lib/qt/bin/rcc \
		images/ranalogo.png
	/usr/lib/qt/bin/rcc -name images images.qrc -o qrc_images.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_control.cpp moc_runner.cpp moc_eventdialog.cpp moc_postcontrol.cpp moc_eventrunner.cpp moc_helpdialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_control.cpp moc_runner.cpp moc_eventdialog.cpp moc_postcontrol.cpp moc_eventrunner.cpp moc_helpdialog.cpp
moc_mainwindow.cpp: graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		agentengine/agents/autonLUA.h \
		agentengine/agents/nestene.h \
		agentengine/agents/master.h \
		eventqueue.h \
		utility.h \
		agentengine/agents/autonlistener.h \
		agentengine/agents/auton.h \
		agentengine/agents/autonscreamer.h \
		mainwindow.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		agentengine/agentdomain.h \
		agentengine/agents/doctor.h \
		runner.h \
		postprocessing/graphics/zmap.h \
		mainwindow.h \
		/usr/lib/qt/bin/moc
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/sojoe/qtProjects/Rana_qt -I/home/sojoe/qtProjects/lua51_64bit/include -I/usr/include/luajit-2.0 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include-fixed -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_control.cpp: mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		agentengine/agents/autonLUA.h \
		agentengine/agents/nestene.h \
		agentengine/agents/master.h \
		eventqueue.h \
		utility.h \
		agentengine/agents/autonlistener.h \
		agentengine/agents/auton.h \
		agentengine/agents/autonscreamer.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		agentengine/agentdomain.h \
		agentengine/agents/doctor.h \
		runner.h \
		postprocessing/graphics/zmap.h \
		control.h \
		/usr/lib/qt/bin/moc
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/sojoe/qtProjects/Rana_qt -I/home/sojoe/qtProjects/lua51_64bit/include -I/usr/include/luajit-2.0 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include-fixed -I/usr/include control.h -o moc_control.cpp

moc_runner.cpp: agentengine/agentdomain.h \
		agentengine/agents/master.h \
		eventqueue.h \
		agentengine/agents/nestene.h \
		agentengine/agents/autonlistener.h \
		agentengine/agents/auton.h \
		agentengine/agents/autonscreamer.h \
		agentengine/agents/autonLUA.h \
		utility.h \
		agentengine/agents/doctor.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		runner.h \
		postprocessing/graphics/zmap.h \
		runner.h \
		/usr/lib/qt/bin/moc
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/sojoe/qtProjects/Rana_qt -I/home/sojoe/qtProjects/lua51_64bit/include -I/usr/include/luajit-2.0 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include-fixed -I/usr/include runner.h -o moc_runner.cpp

moc_eventdialog.cpp: control.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		agentengine/agents/autonLUA.h \
		agentengine/agents/nestene.h \
		agentengine/agents/master.h \
		eventqueue.h \
		utility.h \
		agentengine/agents/autonlistener.h \
		agentengine/agents/auton.h \
		agentengine/agents/autonscreamer.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		postprocessing/graphics/zmap.h \
		agentengine/agentdomain.h \
		agentengine/agents/doctor.h \
		runner.h \
		eventdialog.h \
		/usr/lib/qt/bin/moc
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/sojoe/qtProjects/Rana_qt -I/home/sojoe/qtProjects/lua51_64bit/include -I/usr/include/luajit-2.0 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include-fixed -I/usr/include eventdialog.h -o moc_eventdialog.cpp

moc_postcontrol.cpp: postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		agentengine/agents/autonLUA.h \
		agentengine/agents/nestene.h \
		agentengine/agents/master.h \
		eventqueue.h \
		utility.h \
		agentengine/agents/autonlistener.h \
		agentengine/agents/auton.h \
		agentengine/agents/autonscreamer.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		agentengine/agentdomain.h \
		agentengine/agents/doctor.h \
		runner.h \
		postprocessing/graphics/zmap.h \
		postprocessing/postcontrol.h \
		/usr/lib/qt/bin/moc
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/sojoe/qtProjects/Rana_qt -I/home/sojoe/qtProjects/lua51_64bit/include -I/usr/include/luajit-2.0 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include-fixed -I/usr/include postprocessing/postcontrol.h -o moc_postcontrol.cpp

moc_eventrunner.cpp: postprocessing/eventprocessing.h \
		agentengine/agents/autonLUA.h \
		agentengine/agents/nestene.h \
		agentengine/agents/master.h \
		eventqueue.h \
		utility.h \
		agentengine/agents/autonlistener.h \
		agentengine/agents/auton.h \
		agentengine/agents/autonscreamer.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		agentengine/agentdomain.h \
		agentengine/agents/doctor.h \
		runner.h \
		postprocessing/graphics/zmap.h \
		postprocessing/eventrunner.h \
		/usr/lib/qt/bin/moc
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/sojoe/qtProjects/Rana_qt -I/home/sojoe/qtProjects/lua51_64bit/include -I/usr/include/luajit-2.0 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include-fixed -I/usr/include postprocessing/eventrunner.h -o moc_eventrunner.cpp

moc_helpdialog.cpp: helpdialog.h \
		/usr/lib/qt/bin/moc
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/sojoe/qtProjects/Rana_qt -I/home/sojoe/qtProjects/lua51_64bit/include -I/usr/include/luajit-2.0 -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include-fixed -I/usr/include helpdialog.h -o moc_helpdialog.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_eventdialog.h ui_about.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_eventdialog.h ui_about.h
ui_mainwindow.h: mainwindow.ui \
		/usr/lib/qt/bin/uic
	/usr/lib/qt/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_eventdialog.h: eventdialog.ui \
		/usr/lib/qt/bin/uic
	/usr/lib/qt/bin/uic eventdialog.ui -o ui_eventdialog.h

ui_about.h: about.ui \
		/usr/lib/qt/bin/uic
	/usr/lib/qt/bin/uic about.ui -o ui_about.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		agentengine/agents/autonLUA.h \
		agentengine/agents/nestene.h \
		agentengine/agents/master.h \
		eventqueue.h \
		utility.h \
		agentengine/agents/autonlistener.h \
		agentengine/agents/auton.h \
		agentengine/agents/autonscreamer.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		agentengine/agentdomain.h \
		agentengine/agents/doctor.h \
		runner.h \
		postprocessing/graphics/zmap.h \
		ID.h \
		physics/phys.h \
		output.h \
		physics/gridmovement.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		agentengine/agents/autonLUA.h \
		agentengine/agents/nestene.h \
		agentengine/agents/master.h \
		eventqueue.h \
		utility.h \
		agentengine/agents/autonlistener.h \
		agentengine/agents/auton.h \
		agentengine/agents/autonscreamer.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		agentengine/agentdomain.h \
		agentengine/agents/doctor.h \
		runner.h \
		postprocessing/graphics/zmap.h \
		ui_mainwindow.h \
		physics/maphandler.h \
		physics/phys.h \
		physics/gridmovement.h \
		output.h \
		eventdialog.h \
		helpdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

eventqueue.o: eventqueue.cpp eventqueue.h \
		output.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		agentengine/agents/autonLUA.h \
		agentengine/agents/nestene.h \
		agentengine/agents/master.h \
		utility.h \
		agentengine/agents/autonlistener.h \
		agentengine/agents/auton.h \
		agentengine/agents/autonscreamer.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		agentengine/agentdomain.h \
		agentengine/agents/doctor.h \
		runner.h \
		postprocessing/graphics/zmap.h \
		ID.h \
		physics/phys.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o eventqueue.o eventqueue.cpp

phys.o: physics/phys.cpp physics/phys.h \
		output.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		agentengine/agents/autonLUA.h \
		agentengine/agents/nestene.h \
		agentengine/agents/master.h \
		eventqueue.h \
		utility.h \
		agentengine/agents/autonlistener.h \
		agentengine/agents/auton.h \
		agentengine/agents/autonscreamer.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		agentengine/agentdomain.h \
		agentengine/agents/doctor.h \
		runner.h \
		postprocessing/graphics/zmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o phys.o physics/phys.cpp

nestene.o: agentengine/agents/nestene.cpp physics/phys.h \
		agentengine/agents/nestene.h \
		agentengine/agents/master.h \
		eventqueue.h \
		utility.h \
		agentengine/agents/autonlistener.h \
		agentengine/agents/auton.h \
		agentengine/agents/autonscreamer.h \
		agentengine/agents/autonLUA.h \
		agentengine/agents/doctor.h \
		ID.h \
		output.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		agentengine/agentdomain.h \
		runner.h \
		postprocessing/graphics/zmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nestene.o agentengine/agents/nestene.cpp

auton.o: agentengine/agents/auton.cpp agentengine/agents/auton.h \
		eventqueue.h \
		agentengine/agents/nestene.h \
		agentengine/agents/master.h \
		utility.h \
		agentengine/agents/autonlistener.h \
		agentengine/agents/autonscreamer.h \
		agentengine/agents/autonLUA.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o auton.o agentengine/agents/auton.cpp

autonlistener.o: agentengine/agents/autonlistener.cpp ID.h \
		agentengine/agents/autonlistener.h \
		agentengine/agents/auton.h \
		eventqueue.h \
		physics/phys.h \
		output.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		agentengine/agents/autonLUA.h \
		agentengine/agents/nestene.h \
		agentengine/agents/master.h \
		utility.h \
		agentengine/agents/autonscreamer.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		agentengine/agentdomain.h \
		agentengine/agents/doctor.h \
		runner.h \
		postprocessing/graphics/zmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o autonlistener.o agentengine/agents/autonlistener.cpp

autonLUA.o: agentengine/agents/autonLUA.cpp output.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		agentengine/agents/autonLUA.h \
		agentengine/agents/nestene.h \
		agentengine/agents/master.h \
		eventqueue.h \
		utility.h \
		agentengine/agents/autonlistener.h \
		agentengine/agents/auton.h \
		agentengine/agents/autonscreamer.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		agentengine/agentdomain.h \
		agentengine/agents/doctor.h \
		runner.h \
		postprocessing/graphics/zmap.h \
		ID.h \
		physics/phys.h \
		physics/gridmovement.h \
		physics/maphandler.h \
		physics/shared.h \
		physics/scanning.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o autonLUA.o agentengine/agents/autonLUA.cpp

autonscreamer.o: agentengine/agents/autonscreamer.cpp ID.h \
		agentengine/agents/autonscreamer.h \
		agentengine/agents/auton.h \
		eventqueue.h \
		output.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		agentengine/agents/autonLUA.h \
		agentengine/agents/nestene.h \
		agentengine/agents/master.h \
		utility.h \
		agentengine/agents/autonlistener.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		agentengine/agentdomain.h \
		agentengine/agents/doctor.h \
		runner.h \
		postprocessing/graphics/zmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o autonscreamer.o agentengine/agents/autonscreamer.cpp

doctor.o: agentengine/agents/doctor.cpp agentengine/agents/doctor.h \
		agentengine/agents/auton.h \
		eventqueue.h \
		agentengine/agents/master.h \
		agentengine/agents/nestene.h \
		agentengine/agents/autonlistener.h \
		agentengine/agents/autonscreamer.h \
		agentengine/agents/autonLUA.h \
		utility.h \
		output.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		agentengine/agentdomain.h \
		runner.h \
		postprocessing/graphics/zmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o doctor.o agentengine/agents/doctor.cpp

master.o: agentengine/agents/master.cpp agentengine/agents/master.h \
		eventqueue.h \
		agentengine/agents/nestene.h \
		agentengine/agents/autonlistener.h \
		agentengine/agents/auton.h \
		agentengine/agents/autonscreamer.h \
		agentengine/agents/autonLUA.h \
		utility.h \
		physics/phys.h \
		output.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		agentengine/agentdomain.h \
		agentengine/agents/doctor.h \
		runner.h \
		postprocessing/graphics/zmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o master.o agentengine/agents/master.cpp

agentdomain.o: agentengine/agentdomain.cpp agentengine/agentdomain.h \
		agentengine/agents/master.h \
		eventqueue.h \
		agentengine/agents/nestene.h \
		agentengine/agents/autonlistener.h \
		agentengine/agents/auton.h \
		agentengine/agents/autonscreamer.h \
		agentengine/agents/autonLUA.h \
		utility.h \
		agentengine/agents/doctor.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		runner.h \
		postprocessing/graphics/zmap.h \
		physics/phys.h \
		physics/gridmovement.h \
		physics/shared.h \
		output.h \
		ID.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o agentdomain.o agentengine/agentdomain.cpp

output.o: output.cpp physics/phys.h \
		output.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		agentengine/agents/autonLUA.h \
		agentengine/agents/nestene.h \
		agentengine/agents/master.h \
		eventqueue.h \
		utility.h \
		agentengine/agents/autonlistener.h \
		agentengine/agents/auton.h \
		agentengine/agents/autonscreamer.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		agentengine/agentdomain.h \
		agentengine/agents/doctor.h \
		runner.h \
		postprocessing/graphics/zmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o output.o output.cpp

maphandler.o: physics/maphandler.cpp output.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		agentengine/agents/autonLUA.h \
		agentengine/agents/nestene.h \
		agentengine/agents/master.h \
		eventqueue.h \
		utility.h \
		agentengine/agents/autonlistener.h \
		agentengine/agents/auton.h \
		agentengine/agents/autonscreamer.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		agentengine/agentdomain.h \
		agentengine/agents/doctor.h \
		runner.h \
		postprocessing/graphics/zmap.h \
		physics/phys.h \
		physics/maphandler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o maphandler.o physics/maphandler.cpp

control.o: control.cpp control.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		agentengine/agents/autonLUA.h \
		agentengine/agents/nestene.h \
		agentengine/agents/master.h \
		eventqueue.h \
		utility.h \
		agentengine/agents/autonlistener.h \
		agentengine/agents/auton.h \
		agentengine/agents/autonscreamer.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		postprocessing/graphics/zmap.h \
		agentengine/agentdomain.h \
		agentengine/agents/doctor.h \
		runner.h \
		output.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o control.o control.cpp

agentItem.o: graphics/agentItem.cpp graphics/agentItem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o agentItem.o graphics/agentItem.cpp

gridmovement.o: physics/gridmovement.cpp physics/gridmovement.h \
		output.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		agentengine/agents/autonLUA.h \
		agentengine/agents/nestene.h \
		agentengine/agents/master.h \
		eventqueue.h \
		utility.h \
		agentengine/agents/autonlistener.h \
		agentengine/agents/auton.h \
		agentengine/agents/autonscreamer.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		agentengine/agentdomain.h \
		agentengine/agents/doctor.h \
		runner.h \
		postprocessing/graphics/zmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gridmovement.o physics/gridmovement.cpp

runner.o: runner.cpp runner.h \
		agentengine/agentdomain.h \
		agentengine/agents/master.h \
		eventqueue.h \
		agentengine/agents/nestene.h \
		agentengine/agents/autonlistener.h \
		agentengine/agents/auton.h \
		agentengine/agents/autonscreamer.h \
		agentengine/agents/autonLUA.h \
		utility.h \
		agentengine/agents/doctor.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		postprocessing/graphics/zmap.h \
		output.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o runner.o runner.cpp

shared.o: physics/shared.cpp output.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		agentengine/agents/autonLUA.h \
		agentengine/agents/nestene.h \
		agentengine/agents/master.h \
		eventqueue.h \
		utility.h \
		agentengine/agents/autonlistener.h \
		agentengine/agents/auton.h \
		agentengine/agents/autonscreamer.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		agentengine/agentdomain.h \
		agentengine/agents/doctor.h \
		runner.h \
		postprocessing/graphics/zmap.h \
		physics/shared.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o shared.o physics/shared.cpp

eventprocessing.o: postprocessing/eventprocessing.cpp physics/phys.h \
		postprocessing/eventprocessing.h \
		agentengine/agents/autonLUA.h \
		agentengine/agents/nestene.h \
		agentengine/agents/master.h \
		eventqueue.h \
		utility.h \
		agentengine/agents/autonlistener.h \
		agentengine/agents/auton.h \
		agentengine/agents/autonscreamer.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		agentengine/agentdomain.h \
		agentengine/agents/doctor.h \
		runner.h \
		postprocessing/graphics/zmap.h \
		output.h \
		physics/shared.h \
		physics/gridmovement.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o eventprocessing.o postprocessing/eventprocessing.cpp

eventmap.o: postprocessing/eventmap.cpp postprocessing/eventmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o eventmap.o postprocessing/eventmap.cpp

zcolormap.o: graphics/zcolormap.cpp graphics/zcolormap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zcolormap.o graphics/zcolormap.cpp

colorutility.o: postprocessing/colorutility.cpp postprocessing/colorutility.h \
		output.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		agentengine/agents/autonLUA.h \
		agentengine/agents/nestene.h \
		agentengine/agents/master.h \
		eventqueue.h \
		utility.h \
		agentengine/agents/autonlistener.h \
		agentengine/agents/auton.h \
		agentengine/agents/autonscreamer.h \
		postprocessing/graphics/zblock.h \
		control.h \
		agentengine/agentdomain.h \
		agentengine/agents/doctor.h \
		runner.h \
		postprocessing/graphics/zmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o colorutility.o postprocessing/colorutility.cpp

eventdialog.o: eventdialog.cpp eventdialog.h \
		control.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		agentengine/agents/autonLUA.h \
		agentengine/agents/nestene.h \
		agentengine/agents/master.h \
		eventqueue.h \
		utility.h \
		agentengine/agents/autonlistener.h \
		agentengine/agents/auton.h \
		agentengine/agents/autonscreamer.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		postprocessing/graphics/zmap.h \
		agentengine/agentdomain.h \
		agentengine/agents/doctor.h \
		runner.h \
		ui_eventdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o eventdialog.o eventdialog.cpp

zblock.o: postprocessing/graphics/zblock.cpp output.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		agentengine/agents/autonLUA.h \
		agentengine/agents/nestene.h \
		agentengine/agents/master.h \
		eventqueue.h \
		utility.h \
		agentengine/agents/autonlistener.h \
		agentengine/agents/auton.h \
		agentengine/agents/autonscreamer.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		agentengine/agentdomain.h \
		agentengine/agents/doctor.h \
		runner.h \
		postprocessing/graphics/zmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zblock.o postprocessing/graphics/zblock.cpp

postcontrol.o: postprocessing/postcontrol.cpp postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		agentengine/agents/autonLUA.h \
		agentengine/agents/nestene.h \
		agentengine/agents/master.h \
		eventqueue.h \
		utility.h \
		agentengine/agents/autonlistener.h \
		agentengine/agents/auton.h \
		agentengine/agents/autonscreamer.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		agentengine/agentdomain.h \
		agentengine/agents/doctor.h \
		runner.h \
		postprocessing/graphics/zmap.h \
		output.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o postcontrol.o postprocessing/postcontrol.cpp

eventrunner.o: postprocessing/eventrunner.cpp postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		agentengine/agents/autonLUA.h \
		agentengine/agents/nestene.h \
		agentengine/agents/master.h \
		eventqueue.h \
		utility.h \
		agentengine/agents/autonlistener.h \
		agentengine/agents/auton.h \
		agentengine/agents/autonscreamer.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		agentengine/agentdomain.h \
		agentengine/agents/doctor.h \
		runner.h \
		postprocessing/graphics/zmap.h \
		output.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o eventrunner.o postprocessing/eventrunner.cpp

zmap.o: postprocessing/graphics/zmap.cpp postprocessing/graphics/zmap.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		output.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		agentengine/agents/autonLUA.h \
		agentengine/agents/nestene.h \
		agentengine/agents/master.h \
		eventqueue.h \
		utility.h \
		agentengine/agents/autonlistener.h \
		agentengine/agents/auton.h \
		agentengine/agents/autonscreamer.h \
		control.h \
		agentengine/agentdomain.h \
		agentengine/agents/doctor.h \
		runner.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zmap.o postprocessing/graphics/zmap.cpp

scanning.o: physics/scanning.cpp physics/scanning.h \
		utility.h \
		output.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		agentengine/agents/autonLUA.h \
		agentengine/agents/nestene.h \
		agentengine/agents/master.h \
		eventqueue.h \
		agentengine/agents/autonlistener.h \
		agentengine/agents/auton.h \
		agentengine/agents/autonscreamer.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		agentengine/agentdomain.h \
		agentengine/agents/doctor.h \
		runner.h \
		postprocessing/graphics/zmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scanning.o physics/scanning.cpp

helpdialog.o: helpdialog.cpp helpdialog.h \
		ui_about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o helpdialog.o helpdialog.cpp

qrc_images.o: qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_images.o qrc_images.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_control.o: moc_control.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_control.o moc_control.cpp

moc_runner.o: moc_runner.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_runner.o moc_runner.cpp

moc_eventdialog.o: moc_eventdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_eventdialog.o moc_eventdialog.cpp

moc_postcontrol.o: moc_postcontrol.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_postcontrol.o moc_postcontrol.cpp

moc_eventrunner.o: moc_eventrunner.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_eventrunner.o moc_eventrunner.cpp

moc_helpdialog.o: moc_helpdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_helpdialog.o moc_helpdialog.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

