#############################################################################
# Makefile for building: Rana_qt
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  Rana_qt.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake CONFIG+=release -o Makefile Rana_qt.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -Wextra -Wno-unused-variable -Wno-unused-parameter -O2 -o3 -std=c++1y -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/home/theis/workspace/RANA/../lua51_64bit/include -isystem /usr/include/lua5.1 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Rana_qt1.0.0
DISTDIR = /home/theis/workspace/RANA/.tmp/Rana_qt1.0.0
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -llua5.1 -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		output.cpp \
		control.cpp \
		graphics/agentItem.cpp \
		runner.cpp \
		postprocessing/eventprocessing.cpp \
		postprocessing/colorutility.cpp \
		eventdialog.cpp \
		postprocessing/graphics/zblock.cpp \
		postprocessing/postcontrol.cpp \
		postprocessing/eventrunner.cpp \
		postprocessing/graphics/zmap.cpp \
		helpdialog.cpp \
		api/gridmovement.cpp \
		api/maphandler.cpp \
		api/phys.cpp \
		api/scanning.cpp \
		api/shared.cpp \
		simulationcore/flowcontrol.cpp \
		simulationcore/interfacer.cpp \
		simulationcore/sector.cpp \
		simulationcore/supervisor.cpp \
		simulationcore/agents/agent.cpp \
		simulationcore/agents/agentinterface.cpp \
		simulationcore/agents/agentluainterface.cpp \
		simulationcore/eventqueue.cpp qrc_images.cpp \
		moc_mainwindow.cpp \
		moc_control.cpp \
		moc_runner.cpp \
		moc_eventdialog.cpp \
		moc_postcontrol.cpp \
		moc_eventrunner.cpp \
		moc_helpdialog.cpp
OBJECTS       = main.o \
		mainwindow.o \
		output.o \
		control.o \
		agentItem.o \
		runner.o \
		eventprocessing.o \
		colorutility.o \
		eventdialog.o \
		zblock.o \
		postcontrol.o \
		eventrunner.o \
		zmap.o \
		helpdialog.o \
		gridmovement.o \
		maphandler.o \
		phys.o \
		scanning.o \
		shared.o \
		flowcontrol.o \
		interfacer.o \
		sector.o \
		supervisor.o \
		agent.o \
		agentinterface.o \
		agentluainterface.o \
		eventqueue.o \
		qrc_images.o \
		moc_mainwindow.o \
		moc_control.o \
		moc_runner.o \
		moc_eventdialog.o \
		moc_postcontrol.o \
		moc_eventrunner.o \
		moc_helpdialog.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++14.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Rana_qt.pro mainwindow.h \
		ID.h \
		utility.h \
		output.h \
		control.h \
		graphics/agentItem.h \
		runner.h \
		postprocessing/eventprocessing.h \
		postprocessing/colorutility.h \
		eventdialog.h \
		postprocessing/graphics/zblock.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/graphics/zmap.h \
		helpdialog.h \
		api/gridmovement.h \
		api/maphandler.h \
		api/phys.h \
		api/scanning.h \
		api/shared.h \
		simulationcore/flowcontrol.h \
		simulationcore/interfacer.h \
		simulationcore/sector.h \
		simulationcore/supervisor.h \
		simulationcore/agents/agent.h \
		simulationcore/agents/agentinterface.h \
		simulationcore/agents/agentluainterface.h \
		simulationcore/eventqueue.h main.cpp \
		mainwindow.cpp \
		output.cpp \
		control.cpp \
		graphics/agentItem.cpp \
		runner.cpp \
		postprocessing/eventprocessing.cpp \
		postprocessing/colorutility.cpp \
		eventdialog.cpp \
		postprocessing/graphics/zblock.cpp \
		postprocessing/postcontrol.cpp \
		postprocessing/eventrunner.cpp \
		postprocessing/graphics/zmap.cpp \
		helpdialog.cpp \
		api/gridmovement.cpp \
		api/maphandler.cpp \
		api/phys.cpp \
		api/scanning.cpp \
		api/shared.cpp \
		simulationcore/flowcontrol.cpp \
		simulationcore/interfacer.cpp \
		simulationcore/sector.cpp \
		simulationcore/supervisor.cpp \
		simulationcore/agents/agent.cpp \
		simulationcore/agents/agentinterface.cpp \
		simulationcore/agents/agentluainterface.cpp \
		simulationcore/eventqueue.cpp
QMAKE_TARGET  = Rana_qt
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = Rana_qt


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_mainwindow.h ui_eventdialog.h ui_about.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Rana_qt.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++14.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Rana_qt.pro \
		images.qrc \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) CONFIG+=release -o Makefile Rana_qt.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++14.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
Rana_qt.pro:
images.qrc:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) CONFIG+=release -o Makefile Rana_qt.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents images.qrc $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h ID.h utility.h output.h control.h graphics/agentItem.h runner.h postprocessing/eventprocessing.h postprocessing/colorutility.h eventdialog.h postprocessing/graphics/zblock.h postprocessing/postcontrol.h postprocessing/eventrunner.h postprocessing/graphics/zmap.h helpdialog.h api/gridmovement.h api/maphandler.h api/phys.h api/scanning.h api/shared.h simulationcore/flowcontrol.h simulationcore/interfacer.h simulationcore/sector.h simulationcore/supervisor.h simulationcore/agents/agent.h simulationcore/agents/agentinterface.h simulationcore/agents/agentluainterface.h simulationcore/eventqueue.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp output.cpp control.cpp graphics/agentItem.cpp runner.cpp postprocessing/eventprocessing.cpp postprocessing/colorutility.cpp eventdialog.cpp postprocessing/graphics/zblock.cpp postprocessing/postcontrol.cpp postprocessing/eventrunner.cpp postprocessing/graphics/zmap.cpp helpdialog.cpp api/gridmovement.cpp api/maphandler.cpp api/phys.cpp api/scanning.cpp api/shared.cpp simulationcore/flowcontrol.cpp simulationcore/interfacer.cpp simulationcore/sector.cpp simulationcore/supervisor.cpp simulationcore/agents/agent.cpp simulationcore/agents/agentinterface.cpp simulationcore/agents/agentluainterface.cpp simulationcore/eventqueue.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui eventdialog.ui about.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

first: $(first) copydata

copydata:
	$(COPY_DIR) /home/theis/workspace/RANA/modules /home/theis/workspace/RANA

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_images.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_images.cpp
qrc_images.cpp: images.qrc \
		images/ranalogo.png
	/usr/lib/x86_64-linux-gnu/qt5/bin/rcc -name images images.qrc -o qrc_images.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_control.cpp moc_runner.cpp moc_eventdialog.cpp moc_postcontrol.cpp moc_eventrunner.cpp moc_helpdialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_control.cpp moc_runner.cpp moc_eventdialog.cpp moc_postcontrol.cpp moc_eventrunner.cpp moc_helpdialog.cpp
moc_mainwindow.cpp: graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		simulationcore/agents/agentluainterface.h \
		simulationcore/sector.h \
		simulationcore/supervisor.h \
		simulationcore/eventqueue.h \
		utility.h \
		simulationcore/agents/agentinterface.h \
		simulationcore/agents/agent.h \
		mainwindow.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		simulationcore/flowcontrol.h \
		simulationcore/interfacer.h \
		runner.h \
		postprocessing/graphics/zmap.h \
		mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/theis/workspace/RANA -I/home/theis/workspace/lua51_64bit/include -I/usr/include/lua5.1 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_control.cpp: mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		simulationcore/agents/agentluainterface.h \
		simulationcore/sector.h \
		simulationcore/supervisor.h \
		simulationcore/eventqueue.h \
		utility.h \
		simulationcore/agents/agentinterface.h \
		simulationcore/agents/agent.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		simulationcore/flowcontrol.h \
		simulationcore/interfacer.h \
		runner.h \
		postprocessing/graphics/zmap.h \
		control.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/theis/workspace/RANA -I/home/theis/workspace/lua51_64bit/include -I/usr/include/lua5.1 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include control.h -o moc_control.cpp

moc_runner.cpp: simulationcore/flowcontrol.h \
		simulationcore/supervisor.h \
		simulationcore/eventqueue.h \
		simulationcore/sector.h \
		simulationcore/agents/agentinterface.h \
		simulationcore/agents/agent.h \
		utility.h \
		simulationcore/agents/agentluainterface.h \
		simulationcore/interfacer.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		runner.h \
		postprocessing/graphics/zmap.h \
		runner.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/theis/workspace/RANA -I/home/theis/workspace/lua51_64bit/include -I/usr/include/lua5.1 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include runner.h -o moc_runner.cpp

moc_eventdialog.cpp: control.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		simulationcore/agents/agentluainterface.h \
		simulationcore/sector.h \
		simulationcore/supervisor.h \
		simulationcore/eventqueue.h \
		utility.h \
		simulationcore/agents/agentinterface.h \
		simulationcore/agents/agent.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		postprocessing/graphics/zmap.h \
		simulationcore/flowcontrol.h \
		simulationcore/interfacer.h \
		runner.h \
		eventdialog.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/theis/workspace/RANA -I/home/theis/workspace/lua51_64bit/include -I/usr/include/lua5.1 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include eventdialog.h -o moc_eventdialog.cpp

moc_postcontrol.cpp: postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		simulationcore/agents/agentluainterface.h \
		simulationcore/sector.h \
		simulationcore/supervisor.h \
		simulationcore/eventqueue.h \
		utility.h \
		simulationcore/agents/agentinterface.h \
		simulationcore/agents/agent.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		simulationcore/flowcontrol.h \
		simulationcore/interfacer.h \
		runner.h \
		postprocessing/graphics/zmap.h \
		postprocessing/postcontrol.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/theis/workspace/RANA -I/home/theis/workspace/lua51_64bit/include -I/usr/include/lua5.1 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include postprocessing/postcontrol.h -o moc_postcontrol.cpp

moc_eventrunner.cpp: postprocessing/eventprocessing.h \
		simulationcore/agents/agentluainterface.h \
		simulationcore/sector.h \
		simulationcore/supervisor.h \
		simulationcore/eventqueue.h \
		utility.h \
		simulationcore/agents/agentinterface.h \
		simulationcore/agents/agent.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		simulationcore/flowcontrol.h \
		simulationcore/interfacer.h \
		runner.h \
		postprocessing/graphics/zmap.h \
		postprocessing/eventrunner.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/theis/workspace/RANA -I/home/theis/workspace/lua51_64bit/include -I/usr/include/lua5.1 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include postprocessing/eventrunner.h -o moc_eventrunner.cpp

moc_helpdialog.cpp: helpdialog.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/theis/workspace/RANA -I/home/theis/workspace/lua51_64bit/include -I/usr/include/lua5.1 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include helpdialog.h -o moc_helpdialog.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_eventdialog.h ui_about.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_eventdialog.h ui_about.h
ui_mainwindow.h: mainwindow.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_eventdialog.h: eventdialog.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic eventdialog.ui -o ui_eventdialog.h

ui_about.h: about.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic about.ui -o ui_about.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		simulationcore/agents/agentluainterface.h \
		simulationcore/sector.h \
		simulationcore/supervisor.h \
		simulationcore/eventqueue.h \
		utility.h \
		simulationcore/agents/agentinterface.h \
		simulationcore/agents/agent.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		simulationcore/flowcontrol.h \
		simulationcore/interfacer.h \
		runner.h \
		postprocessing/graphics/zmap.h \
		ID.h \
		api/phys.h \
		output.h \
		api/gridmovement.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		simulationcore/agents/agentluainterface.h \
		simulationcore/sector.h \
		simulationcore/supervisor.h \
		simulationcore/eventqueue.h \
		utility.h \
		simulationcore/agents/agentinterface.h \
		simulationcore/agents/agent.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		simulationcore/flowcontrol.h \
		simulationcore/interfacer.h \
		runner.h \
		postprocessing/graphics/zmap.h \
		ui_mainwindow.h \
		api/maphandler.h \
		api/phys.h \
		api/gridmovement.h \
		output.h \
		eventdialog.h \
		helpdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

output.o: output.cpp api/phys.h \
		output.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		simulationcore/agents/agentluainterface.h \
		simulationcore/sector.h \
		simulationcore/supervisor.h \
		simulationcore/eventqueue.h \
		utility.h \
		simulationcore/agents/agentinterface.h \
		simulationcore/agents/agent.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		simulationcore/flowcontrol.h \
		simulationcore/interfacer.h \
		runner.h \
		postprocessing/graphics/zmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o output.o output.cpp

control.o: control.cpp control.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		simulationcore/agents/agentluainterface.h \
		simulationcore/sector.h \
		simulationcore/supervisor.h \
		simulationcore/eventqueue.h \
		utility.h \
		simulationcore/agents/agentinterface.h \
		simulationcore/agents/agent.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		postprocessing/graphics/zmap.h \
		simulationcore/flowcontrol.h \
		simulationcore/interfacer.h \
		runner.h \
		output.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o control.o control.cpp

agentItem.o: graphics/agentItem.cpp graphics/agentItem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o agentItem.o graphics/agentItem.cpp

runner.o: runner.cpp runner.h \
		simulationcore/flowcontrol.h \
		simulationcore/supervisor.h \
		simulationcore/eventqueue.h \
		simulationcore/sector.h \
		simulationcore/agents/agentinterface.h \
		simulationcore/agents/agent.h \
		utility.h \
		simulationcore/agents/agentluainterface.h \
		simulationcore/interfacer.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		postprocessing/graphics/zmap.h \
		output.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o runner.o runner.cpp

eventprocessing.o: postprocessing/eventprocessing.cpp api/phys.h \
		postprocessing/eventprocessing.h \
		simulationcore/agents/agentluainterface.h \
		simulationcore/sector.h \
		simulationcore/supervisor.h \
		simulationcore/eventqueue.h \
		utility.h \
		simulationcore/agents/agentinterface.h \
		simulationcore/agents/agent.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		simulationcore/flowcontrol.h \
		simulationcore/interfacer.h \
		runner.h \
		postprocessing/graphics/zmap.h \
		output.h \
		api/shared.h \
		api/gridmovement.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o eventprocessing.o postprocessing/eventprocessing.cpp

colorutility.o: postprocessing/colorutility.cpp postprocessing/colorutility.h \
		output.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		simulationcore/agents/agentluainterface.h \
		simulationcore/sector.h \
		simulationcore/supervisor.h \
		simulationcore/eventqueue.h \
		utility.h \
		simulationcore/agents/agentinterface.h \
		simulationcore/agents/agent.h \
		postprocessing/graphics/zblock.h \
		control.h \
		simulationcore/flowcontrol.h \
		simulationcore/interfacer.h \
		runner.h \
		postprocessing/graphics/zmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o colorutility.o postprocessing/colorutility.cpp

eventdialog.o: eventdialog.cpp eventdialog.h \
		control.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		simulationcore/agents/agentluainterface.h \
		simulationcore/sector.h \
		simulationcore/supervisor.h \
		simulationcore/eventqueue.h \
		utility.h \
		simulationcore/agents/agentinterface.h \
		simulationcore/agents/agent.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		postprocessing/graphics/zmap.h \
		simulationcore/flowcontrol.h \
		simulationcore/interfacer.h \
		runner.h \
		ui_eventdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o eventdialog.o eventdialog.cpp

zblock.o: postprocessing/graphics/zblock.cpp output.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		simulationcore/agents/agentluainterface.h \
		simulationcore/sector.h \
		simulationcore/supervisor.h \
		simulationcore/eventqueue.h \
		utility.h \
		simulationcore/agents/agentinterface.h \
		simulationcore/agents/agent.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		simulationcore/flowcontrol.h \
		simulationcore/interfacer.h \
		runner.h \
		postprocessing/graphics/zmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zblock.o postprocessing/graphics/zblock.cpp

postcontrol.o: postprocessing/postcontrol.cpp postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		simulationcore/agents/agentluainterface.h \
		simulationcore/sector.h \
		simulationcore/supervisor.h \
		simulationcore/eventqueue.h \
		utility.h \
		simulationcore/agents/agentinterface.h \
		simulationcore/agents/agent.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		simulationcore/flowcontrol.h \
		simulationcore/interfacer.h \
		runner.h \
		postprocessing/graphics/zmap.h \
		output.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o postcontrol.o postprocessing/postcontrol.cpp

eventrunner.o: postprocessing/eventrunner.cpp postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		simulationcore/agents/agentluainterface.h \
		simulationcore/sector.h \
		simulationcore/supervisor.h \
		simulationcore/eventqueue.h \
		utility.h \
		simulationcore/agents/agentinterface.h \
		simulationcore/agents/agent.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		simulationcore/flowcontrol.h \
		simulationcore/interfacer.h \
		runner.h \
		postprocessing/graphics/zmap.h \
		output.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o eventrunner.o postprocessing/eventrunner.cpp

zmap.o: postprocessing/graphics/zmap.cpp postprocessing/graphics/zmap.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		output.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		simulationcore/agents/agentluainterface.h \
		simulationcore/sector.h \
		simulationcore/supervisor.h \
		simulationcore/eventqueue.h \
		utility.h \
		simulationcore/agents/agentinterface.h \
		simulationcore/agents/agent.h \
		control.h \
		simulationcore/flowcontrol.h \
		simulationcore/interfacer.h \
		runner.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zmap.o postprocessing/graphics/zmap.cpp

helpdialog.o: helpdialog.cpp helpdialog.h \
		ui_about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o helpdialog.o helpdialog.cpp

gridmovement.o: api/gridmovement.cpp api/gridmovement.h \
		output.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		simulationcore/agents/agentluainterface.h \
		simulationcore/sector.h \
		simulationcore/supervisor.h \
		simulationcore/eventqueue.h \
		utility.h \
		simulationcore/agents/agentinterface.h \
		simulationcore/agents/agent.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		simulationcore/flowcontrol.h \
		simulationcore/interfacer.h \
		runner.h \
		postprocessing/graphics/zmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gridmovement.o api/gridmovement.cpp

maphandler.o: api/maphandler.cpp output.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		simulationcore/agents/agentluainterface.h \
		simulationcore/sector.h \
		simulationcore/supervisor.h \
		simulationcore/eventqueue.h \
		utility.h \
		simulationcore/agents/agentinterface.h \
		simulationcore/agents/agent.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		simulationcore/flowcontrol.h \
		simulationcore/interfacer.h \
		runner.h \
		postprocessing/graphics/zmap.h \
		api/phys.h \
		api/maphandler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o maphandler.o api/maphandler.cpp

phys.o: api/phys.cpp api/phys.h \
		output.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		simulationcore/agents/agentluainterface.h \
		simulationcore/sector.h \
		simulationcore/supervisor.h \
		simulationcore/eventqueue.h \
		utility.h \
		simulationcore/agents/agentinterface.h \
		simulationcore/agents/agent.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		simulationcore/flowcontrol.h \
		simulationcore/interfacer.h \
		runner.h \
		postprocessing/graphics/zmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o phys.o api/phys.cpp

scanning.o: api/scanning.cpp api/scanning.h \
		utility.h \
		output.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		simulationcore/agents/agentluainterface.h \
		simulationcore/sector.h \
		simulationcore/supervisor.h \
		simulationcore/eventqueue.h \
		simulationcore/agents/agentinterface.h \
		simulationcore/agents/agent.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		simulationcore/flowcontrol.h \
		simulationcore/interfacer.h \
		runner.h \
		postprocessing/graphics/zmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scanning.o api/scanning.cpp

shared.o: api/shared.cpp output.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		simulationcore/agents/agentluainterface.h \
		simulationcore/sector.h \
		simulationcore/supervisor.h \
		simulationcore/eventqueue.h \
		utility.h \
		simulationcore/agents/agentinterface.h \
		simulationcore/agents/agent.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		simulationcore/flowcontrol.h \
		simulationcore/interfacer.h \
		runner.h \
		postprocessing/graphics/zmap.h \
		api/shared.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o shared.o api/shared.cpp

flowcontrol.o: simulationcore/flowcontrol.cpp simulationcore/flowcontrol.h \
		simulationcore/supervisor.h \
		simulationcore/eventqueue.h \
		simulationcore/sector.h \
		simulationcore/agents/agentinterface.h \
		simulationcore/agents/agent.h \
		utility.h \
		simulationcore/agents/agentluainterface.h \
		simulationcore/interfacer.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		runner.h \
		postprocessing/graphics/zmap.h \
		api/phys.h \
		api/gridmovement.h \
		api/shared.h \
		output.h \
		ID.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o flowcontrol.o simulationcore/flowcontrol.cpp

interfacer.o: simulationcore/interfacer.cpp simulationcore/interfacer.h \
		simulationcore/agents/agent.h \
		utility.h \
		simulationcore/eventqueue.h \
		simulationcore/supervisor.h \
		simulationcore/sector.h \
		simulationcore/agents/agentinterface.h \
		simulationcore/agents/agentluainterface.h \
		output.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		simulationcore/flowcontrol.h \
		runner.h \
		postprocessing/graphics/zmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o interfacer.o simulationcore/interfacer.cpp

sector.o: simulationcore/sector.cpp api/phys.h \
		simulationcore/sector.h \
		simulationcore/supervisor.h \
		simulationcore/eventqueue.h \
		utility.h \
		simulationcore/agents/agentinterface.h \
		simulationcore/agents/agent.h \
		simulationcore/agents/agentluainterface.h \
		simulationcore/interfacer.h \
		ID.h \
		output.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		simulationcore/flowcontrol.h \
		runner.h \
		postprocessing/graphics/zmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sector.o simulationcore/sector.cpp

supervisor.o: simulationcore/supervisor.cpp simulationcore/supervisor.h \
		simulationcore/eventqueue.h \
		simulationcore/sector.h \
		simulationcore/agents/agentinterface.h \
		simulationcore/agents/agent.h \
		utility.h \
		simulationcore/agents/agentluainterface.h \
		api/phys.h \
		output.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		simulationcore/flowcontrol.h \
		simulationcore/interfacer.h \
		runner.h \
		postprocessing/graphics/zmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o supervisor.o simulationcore/supervisor.cpp

agent.o: simulationcore/agents/agent.cpp simulationcore/agents/agent.h \
		utility.h \
		simulationcore/eventqueue.h \
		simulationcore/sector.h \
		simulationcore/supervisor.h \
		simulationcore/agents/agentinterface.h \
		simulationcore/agents/agentluainterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o agent.o simulationcore/agents/agent.cpp

agentinterface.o: simulationcore/agents/agentinterface.cpp output.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		simulationcore/agents/agentluainterface.h \
		simulationcore/sector.h \
		simulationcore/supervisor.h \
		simulationcore/eventqueue.h \
		utility.h \
		simulationcore/agents/agentinterface.h \
		simulationcore/agents/agent.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		simulationcore/flowcontrol.h \
		simulationcore/interfacer.h \
		runner.h \
		postprocessing/graphics/zmap.h \
		ID.h \
		api/phys.h \
		api/gridmovement.h \
		api/maphandler.h \
		api/shared.h \
		api/scanning.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o agentinterface.o simulationcore/agents/agentinterface.cpp

agentluainterface.o: simulationcore/agents/agentluainterface.cpp output.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		simulationcore/agents/agentluainterface.h \
		simulationcore/sector.h \
		simulationcore/supervisor.h \
		simulationcore/eventqueue.h \
		utility.h \
		simulationcore/agents/agentinterface.h \
		simulationcore/agents/agent.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		simulationcore/flowcontrol.h \
		simulationcore/interfacer.h \
		runner.h \
		postprocessing/graphics/zmap.h \
		ID.h \
		api/phys.h \
		api/gridmovement.h \
		api/maphandler.h \
		api/shared.h \
		api/scanning.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o agentluainterface.o simulationcore/agents/agentluainterface.cpp

eventqueue.o: simulationcore/eventqueue.cpp simulationcore/eventqueue.h \
		output.h \
		mainwindow.h \
		graphics/agentItem.h \
		postprocessing/postcontrol.h \
		postprocessing/eventrunner.h \
		postprocessing/eventprocessing.h \
		simulationcore/agents/agentluainterface.h \
		simulationcore/sector.h \
		simulationcore/supervisor.h \
		utility.h \
		simulationcore/agents/agentinterface.h \
		simulationcore/agents/agent.h \
		postprocessing/graphics/zblock.h \
		postprocessing/colorutility.h \
		control.h \
		simulationcore/flowcontrol.h \
		simulationcore/interfacer.h \
		runner.h \
		postprocessing/graphics/zmap.h \
		ID.h \
		api/phys.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o eventqueue.o simulationcore/eventqueue.cpp

qrc_images.o: qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_images.o qrc_images.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_control.o: moc_control.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_control.o moc_control.cpp

moc_runner.o: moc_runner.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_runner.o moc_runner.cpp

moc_eventdialog.o: moc_eventdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_eventdialog.o moc_eventdialog.cpp

moc_postcontrol.o: moc_postcontrol.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_postcontrol.o moc_postcontrol.cpp

moc_eventrunner.o: moc_eventrunner.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_eventrunner.o moc_eventrunner.cpp

moc_helpdialog.o: moc_helpdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_helpdialog.o moc_helpdialog.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

